import React,{useEffect,useRef,useState} from 'react';
import {Icon} from './ui';
import {request} from './api';
import './voice-transcript.css';
const stamp=n=>Number.isFinite(n)?`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`:'0:00';
export default function AudioPlayer({url,name='Голосовое сообщение',voice=false,messageId=null,token,transcript:storedTranscript=''}){
 const audio=useRef(null),[playing,setPlaying]=useState(false),[time,setTime]=useState(0),[duration,setDuration]=useState(0),[speed,setSpeed]=useState(()=>{try{const n=Number(localStorage.getItem('volna.voiceSpeed'));return [1,1.5,2].includes(n)?n:1;}catch{return 1;}}),[wave,setWave]=useState([]),[error,setError]=useState(''),[transcript,setTranscript]=useState(storedTranscript),[transcribing,setTranscribing]=useState(false),[showTranscript,setShowTranscript]=useState(false),[transcriptError,setTranscriptError]=useState('');
 useEffect(()=>setTranscript(storedTranscript||''),[storedTranscript]);
 useEffect(()=>{let dead=false,context;const element=audio.current;const stop=e=>{if(e.detail!==element)element?.pause();};const rate=e=>{if([1,1.5,2].includes(e.detail)){setSpeed(e.detail);element.playbackRate=e.detail;}};window.addEventListener('volna-audio-play',stop);window.addEventListener('volna-voice-speed',rate);element.playbackRate=speed;
 (async()=>{try{const blob=await(await fetch(url)).blob();if(blob.size>8*1024*1024)return;context=new AudioContext();const decoded=await context.decodeAudioData(await blob.arrayBuffer());if(dead)return;setDuration(decoded.duration);const data=decoded.getChannelData(0),bars=Array.from({length:48},(_,i)=>{let peak=0;const start=Math.floor(i*data.length/48),end=Math.floor((i+1)*data.length/48);for(let j=start;j<end;j+=Math.max(1,Math.floor((end-start)/100)))peak=Math.max(peak,Math.abs(data[j]));return peak;});const max=Math.max(...bars,.001);setWave(bars.map(x=>Math.max(.07,x/max)));}catch{}finally{context?.close().catch(()=>{});}})();
 return()=>{dead=true;element?.pause();window.removeEventListener('volna-audio-play',stop);window.removeEventListener('volna-voice-speed',rate);};},[url]);
 async function toggle(){try{if(audio.current.paused)await audio.current.play();else audio.current.pause();setError('');}catch{setError('Браузер не воспроизводит этот формат. Скачайте аудио.');}}
 async function transcribe(){if(!messageId||transcribing)return;if(transcript){setShowTranscript(v=>!v);return;}setTranscribing(true);setTranscriptError('');try{const result=await request(`/messages/${messageId}/transcribe`,token,{});setTranscript(result.transcript||'');setShowTranscript(true);}catch(e){setTranscriptError(e.message||'Не удалось распознать аудио.');}finally{setTranscribing(false);}}
 function ended(){setPlaying(false);if(!voice)return;const voices=[...document.querySelectorAll('.messages .voice-player[data-voice="true"] audio')];const index=voices.indexOf(audio.current);if(index>=0)voices[index+1]?.play().catch(()=>{});}
 return <div className="audio-player-wrap"><div className="voice-player" data-voice={voice} data-transcribable={!!(voice&&messageId)}><audio ref={audio} src={url} preload="metadata" onLoadedMetadata={e=>{if(Number.isFinite(e.target.duration))setDuration(e.target.duration);}} onDurationChange={e=>{if(Number.isFinite(e.target.duration))setDuration(e.target.duration);}} onTimeUpdate={e=>setTime(e.target.currentTime)} onPlay={()=>{window.dispatchEvent(new CustomEvent('volna-audio-play',{detail:audio.current}));setPlaying(true);}} onPause={()=>setPlaying(false)} onEnded={ended} onError={()=>setError('Аудио недоступно в этом браузере')}/><button type="button" className="voice-play" aria-label={playing?'Приостановить аудио':'Воспроизвести аудио'} onClick={toggle}><Icon name={playing?'pause':'play'}/></button><div className="voice-body">{!voice&&<strong className="audio-title">{name}</strong>}<div className="wave-seek"><div className={'voice-wave '+(!wave.length?'wave-pending':'')} aria-hidden="true">{(wave.length?wave:Array(48).fill(.12)).map((n,i)=><i key={i} className={i/48<=time/(duration||1)?'played':''} style={{height:`${n*30}px`}}/> )}</div><input aria-label={'Перемотка '+name} type="range" min="0" max={duration||1} step="0.1" value={Math.min(time,duration||1)} disabled={!duration} onChange={e=>{audio.current.currentTime=Number(e.target.value);setTime(Number(e.target.value));}}/></div></div><small className="voice-duration">{time>0?stamp(time)+' / ':''}{duration?stamp(duration):'0:00'}</small><button type="button" className="voice-speed" aria-label="Скорость воспроизведения" onClick={()=>{const next=({1:1.5,1.5:2,2:1})[speed];setSpeed(next);audio.current.playbackRate=next;window.dispatchEvent(new CustomEvent('volna-voice-speed',{detail:next}));try{localStorage.setItem('volna.voiceSpeed',String(next));}catch{}}}>{speed}×</button>{voice&&messageId&&<button type="button" className={'transcribe-button '+(transcribing?'is-loading':'')} aria-label={transcribing?'Идёт распознавание голосового':'Распознать голосовое'} aria-expanded={showTranscript} disabled={transcribing} onClick={transcribe}>{transcribing?<i aria-hidden="true"/>:'А'}</button>}{error&&<small role="alert">{error}</small>}</div>{showTranscript&&transcript&&<p className="transcript-text" aria-live="polite">{transcript}</p>}{transcriptError&&<small className="transcript-error" role="alert">{transcriptError}</small>}</div>;
}
