import React,{useState,useEffect,useRef} from 'react';
import {request,messageId,API} from './api';
import {Avatar,Icon} from './ui';
const roles={owner:'Владелец',admin:'Администратор',member:'Участник'};
function Shell({title,onClose,children}){return <div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-label={title} className="modal community-modal"><header><h2>{title}</h2><button type="button" aria-label="Закрыть сообщество" onClick={onClose}>×</button></header>{children}</section></div>;}
export function CreateCommunity({token,onClose,onCreated}){
 const [kind,setKind]=useState('group'),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const retry=useRef(null);
 async function create(e){e.preventDefault();setBusy(true);setError('');try{const signature=JSON.stringify({kind,title,description});if(retry.current?.signature!==signature)retry.current={signature,id:messageId()};const c=await request('/communities',token,{kind,title,description,client_id:retry.current.id});await onCreated(c.id);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <Shell title="Новое сообщество" onClose={onClose}><div className="tabs"><button className={kind==='group'?'selected':''} onClick={()=>setKind('group')}>Группа</button><button className={kind==='channel'?'selected':''} onClick={()=>setKind('channel')}>Канал</button></div><p>{kind==='group'?'Общий разговор: сообщения могут отправлять все участники.':'Лента публикаций: сообщения отправляют владелец и администраторы.'}</p><form onSubmit={create}><label>Название<input autoFocus aria-label="Название сообщества" required minLength={2} maxLength={80} value={title} onChange={e=>setTitle(e.target.value)} placeholder={kind==='group'?'Команда Волны':'Новости Волны'}/></label><label>Описание<textarea aria-label="Описание сообщества" maxLength={1000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="О чём это пространство"/></label>{error&&<div role="alert" className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Создаём…':kind==='group'?'Создать группу':'Создать канал'}</button></form></Shell>;
}
export function JoinCommunity({token,initial='',onClose,onJoined}){
 const [value,setValue]=useState(initial),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function join(e){e.preventDefault();setBusy(true);setError('');try{let code=value.trim();if(code.includes('://')){const u=new URL(code);code=u.searchParams.get('invite')||'';}const result=await request('/invites/join',token,{token:code});await onJoined(result.id);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <Shell title="Вступить по приглашению" onClose={onClose}><p>Вставьте ссылку или код, который прислал администратор. После вступления станет доступна история сообщества.</p><form onSubmit={join}><label>Ссылка или код<input autoFocus aria-label="Приглашение" required value={value} onChange={e=>setValue(e.target.value)} placeholder="https://…/app?invite=…"/></label>{error&&<div role="alert" className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Подключаем…':'Вступить'}</button></form></Shell>;
}
export function ManageCommunity({token,chat,me,revision,onClose,onChanged,onLeft}){
 const [info,setInfo]=useState(null),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('members');
 const [query,setQuery]=useState(''),[people,setPeople]=useState([]),[invite,setInvite]=useState(''),[confirm,setConfirm]=useState(null),[notice,setNotice]=useState('');const inviteInput=useRef(null);
 const admin=info&&['owner','admin'].includes(info.role);
 async function load(){const data=await request('/communities/'+chat.id,token);setInfo(data);return data;}
 useEffect(()=>{const controller=new AbortController();request('/communities/'+chat.id,token,undefined,controller.signal).then(data=>{setInfo(data);setTitle(data.title);setDescription(data.description);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[chat.id,token]);
 useEffect(()=>{const controller=new AbortController();request('/communities/'+chat.id,token,undefined,controller.signal).then(data=>{setInfo(data);if(!['owner','admin'].includes(data.role))setInvite('');}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[revision,chat.id,token]);
 useEffect(()=>{if(!admin||query.trim().length<2){setPeople([]);return;}const controller=new AbortController();const timer=setTimeout(()=>request('/users?q='+encodeURIComponent(query),token,undefined,controller.signal).then(setPeople).catch(e=>{if(e.name!=='AbortError')setError(e.message);}),250);return()=>{clearTimeout(timer);controller.abort();};},[query,token,admin]);
 async function act(action,data={}){setBusy(true);setError('');setNotice('');try{const result=await request(`/communities/${chat.id}/${action}`,token,data);if(action==='leave'){await onLeft();return;}if(action==='invite'){const base=API||window.location.origin;setInvite(base+'/app?invite='+result.token);}if(action==='revoke-invite')setInvite('');await load();await onChanged();setNotice(action==='settings'?'Изменения сохранены':action==='invite'?'Новая ссылка готова. Предыдущая больше не действует.':'Готово');}catch(e){setError(e.message);}finally{setBusy(false);setConfirm(null);}}
 async function copy(){try{if(!navigator.clipboard)throw Error();await navigator.clipboard.writeText(invite);setNotice('Ссылка скопирована');}catch{inviteInput.current?.select();setNotice('Ссылка выделена — скопируйте её вручную');}}
 return <Shell title="Участники и настройки" onClose={onClose}>{error&&<div role="alert" className="error">{error}</div>}{!info?<p>Загрузка…</p>:<><div className="community-summary"><Avatar name={info.title} id={info.id}/><div><strong>{info.title}</strong><small>{info.kind==='channel'?'Канал':'Группа'} · {info.member_count} / {info.max_members} · {roles[info.role]}</small></div></div>{info.description&&<p className="community-description">{info.description}</p>}{notice&&<div className="community-notice" role="status">{notice}</div>}<div className="tabs"><button className={tab==='members'?'selected':''} onClick={()=>setTab('members')}>Участники</button>{admin&&<><button className={tab==='invite'?'selected':''} onClick={()=>setTab('invite')}>Приглашение</button><button className={tab==='settings'?'selected':''} onClick={()=>setTab('settings')}>Настройки</button></>}</div>
 {tab==='members'&&<>{admin&&<label>Добавить по имени, телефону или @username<input aria-label="Добавить участника по имени, телефону или @username" value={query} onChange={e=>setQuery(e.target.value)} placeholder="От двух символов"/></label>}{admin&&query.trim().length>=2&&<div className="people-results">{people.filter(p=>!info.members.some(m=>m.id===p.id)).map(p=><div className="member-row" key={p.id}><Avatar name={p.name} id={p.id}/><div><strong>{p.name}</strong><small>@{p.username}</small></div><button disabled={busy} onClick={()=>act('add',{user_id:p.id})}>Добавить</button></div>)}</div>}{info.kind==='channel'&&!admin?<p>Список подписчиков виден только администраторам.</p>:<div className="member-list">{info.members.map(p=><div className="member-row" key={p.id} data-user-id={p.id}><Avatar name={p.name} id={p.id}/><div className="member-copy"><strong>{p.name}{p.id===me.id?' (вы)':''}</strong><small>@{p.username} · {roles[p.role]}</small>{info.role==='owner'&&p.id!==me.id&&<select aria-label={'Роль '+p.username} disabled={busy} value={p.role} onChange={e=>act('role',{user_id:p.id,role:e.target.value})}><option value="member">Участник</option><option value="admin">Администратор</option></select>}</div>{admin&&p.id!==me.id&&p.role!=='owner'&&(info.role==='owner'||p.role==='member')&&<button className="danger" disabled={busy} aria-label={'Исключить '+p.username} onClick={()=>setConfirm({title:'Исключить '+p.name+'?',text:'Пользователь потеряет доступ и не сможет вернуться по приглашению, пока исключение не снято.',action:'remove',data:{user_id:p.id}})}>Исключить</button>}{info.role==='owner'&&p.id!==me.id&&<button className="transfer-button" disabled={busy} aria-label={'Передать владение '+p.username} onClick={()=>setConfirm({title:'Передать владение?',text:p.name+' станет владельцем. Вы останетесь администратором и не сможете самостоятельно вернуть владение.',action:'transfer',data:{user_id:p.id}})}>Передать владение</button>}</div>)}</div>}{admin&&info.banned.length>0&&<><h3>Исключённые</h3>{info.banned.map(p=><div className="member-row" key={p.id}><div><strong>{p.name}</strong><small>@{p.username}</small></div><button disabled={busy} onClick={()=>act('unban',{user_id:p.id})}>Снять исключение</button></div>)}</>}</>}
 {tab==='invite'&&admin&&<div className="invite-tools"><p>Ссылка действует 7 дней, максимум 100 новых вступлений. Новая ссылка отменяет предыдущую.</p>{info.invite&&<p>Вступлений: {info.invite.uses} / {info.invite.max_uses}<br/>До {new Date(info.invite.expires).toLocaleString('ru-RU')}</p>}{invite&&<><label>Ссылка приглашения<input aria-label="Ссылка приглашения" ref={inviteInput} value={invite} readOnly onClick={e=>e.currentTarget.select()}/></label><button className="secondary" onClick={copy}>Скопировать ссылку</button></>}<button className="primary" disabled={busy} onClick={()=>info.invite?setConfirm({title:'Заменить приглашение?',text:'Старая ссылка перестанет работать.',action:'invite',data:{}}):act('invite')}>{info.invite?'Создать новую ссылку':'Создать приглашение'}</button>{info.invite&&<button className="danger secondary" disabled={busy} onClick={()=>setConfirm({title:'Отозвать приглашение?',text:'По текущей ссылке больше нельзя будет вступить.',action:'revoke-invite',data:{}})}>Отозвать ссылку</button>}</div>}
 {tab==='settings'&&admin&&<form onSubmit={e=>{e.preventDefault();act('settings',{title,description});}}><label>Название<input aria-label="Изменить название" required minLength={2} maxLength={80} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Описание<textarea aria-label="Изменить описание" maxLength={1000} value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="primary" disabled={busy}>Сохранить настройки</button></form>}
 <footer className="community-footer">{info.role==='owner'?<small>Для выхода сначала передайте владение другому участнику.</small>:<button className="danger" disabled={busy} onClick={()=>setConfirm({title:'Покинуть сообщество?',text:'Вы потеряете доступ к истории. Вернуться можно по действующему приглашению.',action:'leave',data:{}})}>Покинуть {info.kind==='channel'?'канал':'группу'}</button>}</footer>
 {confirm&&<div className="confirm-overlay"><section role="alertdialog" aria-modal="true" aria-label={confirm.title}><h3>{confirm.title}</h3><p>{confirm.text}</p><footer><button disabled={busy} onClick={()=>setConfirm(null)}>Отмена</button><button className="danger" disabled={busy} onClick={()=>act(confirm.action,confirm.data)}>Подтвердить</button></footer></section></div>}</>}</Shell>;
}
