import React,{useState,useEffect,useRef} from 'react';
import {fileBlob,request} from './api';
const cache=new Map();let bytesUsed=0;const maxMemory=8*1024*1024;
export function clearEmojiCache(){cache.clear();bytesUsed=0;window.dispatchEvent(new Event('volna-emoji-cache-cleared'));}
export async function cachedEmojiBlob(id,token){const key=token+':'+id,previous=cache.get(key);if(previous&&Date.now()-previous.at<60000){cache.delete(key);cache.set(key,previous);return previous.promise;}if(previous)bytesUsed-=previous.size;const entry={at:Date.now(),size:0,promise:null};entry.promise=fileBlob(id,token).then(blob=>{if(cache.get(key)===entry){entry.size=blob.size;bytesUsed+=blob.size;while(bytesUsed>maxMemory&&cache.size){const [first,value]=cache.entries().next().value;cache.delete(first);bytesUsed-=value.size;}}return blob;}).catch(e=>{if(cache.get(key)===entry)cache.delete(key);throw e;});cache.set(key,entry);while(cache.size>256){const [first,value]=cache.entries().next().value;cache.delete(first);bytesUsed-=value.size;}return entry.promise;}
export default function EmojiAsset({entity,token,fallback,size='inline'}){
 const root=useRef(null),[visible,setVisible]=useState(()=>typeof IntersectionObserver!=='function'),[url,setUrl]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{const clear=()=>{setUrl('');setRevision(n=>n+1);};window.addEventListener('volna-emoji-cache-cleared',clear);return()=>window.removeEventListener('volna-emoji-cache-cleared',clear);},[]);
 useEffect(()=>{if(visible)return;const io=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){setVisible(true);io.disconnect();}},{rootMargin:'100px'});if(root.current)io.observe(root.current);return()=>io.disconnect();},[visible]);
 useEffect(()=>{if(!visible)return;let live=true,object;setUrl('');(async()=>{let data=entity;if(!data.attachment_id&&data.id)data=await request('/v1/emoji/'+data.id,token);if(!/^[a-f0-9]{48}$/.test(data.attachment_id||''))return;if(data.mime&&data.mime!=='image/png'&&data.mime!=='image/webp')return;const blob=await cachedEmojiBlob(data.attachment_id,token);if(live){object=URL.createObjectURL(blob);setUrl(object);}})().catch(()=>{});return()=>{live=false;if(object)URL.revokeObjectURL(object);};},[entity.id,entity.attachment_id,token,visible,revision]);
 return <span ref={root} className={'emoji-asset emoji-'+size} role="img" data-emoji-fallback={fallback} data-emoji-id={entity.id} aria-label={entity.label||entity.title||fallback}>{url?<img src={url} data-emoji-fallback={fallback} data-emoji-id={entity.id} alt={fallback} draggable="false" onError={()=>setUrl('')}/>:fallback}</span>;
}
