import React,{useState,useEffect,useRef} from 'react';
import {request,uploadFile,messageId} from './api';
import EmojiAsset from './EmojiAsset';
export default function EmojiCatalog({token,query,onPick,initialPack,userId}){
 const retry=useRef(null);
 const [editingPack,setEditingPack]=useState(null);
 async function savePack(){if(!editingPack)return;setBusy(true);setError('');try{await request('/v1/emoji/packs/'+editingPack.id,token,{title:editingPack.title,description:editingPack.description},undefined,'PATCH');setEditingPack(null);setRevision(v=>v+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const [section,setSection]=useState(initialPack?'catalog':'installed'),[packs,setPacks]=useState([]),[packId,setPackId]=useState(initialPack||''),[items,setItems]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0),[more,setMore]=useState(false),[cursor,setCursor]=useState(0),[packMore,setPackMore]=useState(false),[packCursor,setPackCursor]=useState(0),[creating,setCreating]=useState(false),[title,setTitle]=useState(''),[assets,setAssets]=useState([]),[own,setOwn]=useState(false);
 useEffect(()=>{const refresh=()=>setRevision(v=>v+1);window.addEventListener('volna-emoji-packs-updated',refresh);return()=>window.removeEventListener('volna-emoji-packs-updated',refresh);},[]);
 useEffect(()=>{const c=new AbortController();request('/v1/emoji/packs?section='+ (section==='installed'?'installed':'all')+'&q='+encodeURIComponent(section==='packs'?query:''),token,undefined,c.signal).then(async r=>{let rows=r.packs;if(initialPack&&!rows.some(p=>p.id===initialPack)){const shared=await request('/v1/emoji/packs/'+initialPack,token,undefined,c.signal);rows=[shared,...rows];}if(!c.signal.aborted){setPacks(rows);setPackMore(r.more);setPackCursor(r.next_offset);}}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[token,section,revision,query,initialPack]);
 useEffect(()=>{const c=new AbortController();setItems([]);setBusy(true);setError('');const timer=setTimeout(()=>request(`/v1/emoji/search?section=${section==='packs'?'catalog':section}&q=${encodeURIComponent(query)}&pack_id=${packId}`,token,undefined,c.signal).then(r=>{setItems(r.items);setMore(r.more);setCursor(r.next_offset);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setBusy(false);}),150);return()=>{clearTimeout(timer);c.abort();};},[token,query,section,packId,revision]);
 async function nextPacks(){setBusy(true);try{const r=await request('/v1/emoji/packs?offset='+packCursor+'&q='+encodeURIComponent(query),token);setPacks(p=>[...p,...r.packs]);setPackMore(r.more);setPackCursor(r.next_offset);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function preference(path,data,method){setError('');try{await request(path,token,data,undefined,method);setRevision(n=>n+1);}catch(e){setError(e.message);}}
 async function next(){setBusy(true);try{const r=await request(`/v1/emoji/search?section=${section==='packs'?'catalog':section}&q=${encodeURIComponent(query)}&pack_id=${packId}&offset=${cursor}`,token);setItems(a=>[...a,...r.items]);setMore(r.more);setCursor(r.next_offset);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function files(input){setBusy(true);setError('');try{if(input.length+assets.length>200)throw Error('В наборе не больше 200 эмодзи');if(input.length>24)throw Error('За один раз — до 24 файлов');for(const file of input){if(!['image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('PNG или WebP до 5 МБ');const bitmap=await createImageBitmap(file);try{const canvas=document.createElement('canvas');canvas.width=100;canvas.height=100;const context=canvas.getContext('2d'),scale=Math.min(100/bitmap.width,100/bitmap.height);context.drawImage(bitmap,(100-bitmap.width*scale)/2,(100-bitmap.height*scale)/2,bitmap.width*scale,bitmap.height*scale);const png=await new Promise(r=>canvas.toBlob(r,'image/png'));if(!png)throw Error('Не удалось подготовить PNG');const f=await uploadFile(new File([png],file.name.replace(/\.[^.]+$/,'')+'.png',{type:'image/png'}),token);await request('/v1/emoji/uploads',token,{attachment_id:f.id});setAssets(a=>[...a,{attachment_id:f.id,label:file.name.replace(/\.[^.]+$/,''),fallback:'✨',keywords:[]}]);}finally{bitmap.close();}}}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function create(){setBusy(true);setError('');try{const payload={title,description:'',kind:'emoji',public:own,items:assets},signature=JSON.stringify(payload);if(retry.current?.signature!==signature)retry.current={signature,id:messageId()};await request('/v1/emoji/packs',token,{...payload,client_id:retry.current.id});retry.current=null;setCreating(false);setAssets([]);setTitle('');setSection('installed');setRevision(v=>v+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="emoji-catalog"><nav className="emoji-sections">{[['installed','Мои наборы'],['catalog','Все'],['recent','Недавние'],['favorite','Избранные'],['packs','Наборы']].map(([key,label])=><button key={key} type="button" className={section===key?'selected':''} onClick={()=>{setSection(key);setPackId('');}}>{label}</button>)}</nav>
 {error&&<p role="alert" className="emoji-error">{error}<button type="button" onClick={()=>setRevision(v=>v+1)}>Повторить</button></p>}
 {section==='packs'?<div className="emoji-packs">{packs.map(p=><article key={p.id}><strong>{p.title}</strong><small>{p.owner?.name} · {p.items.length} эмодзи</small><div className="pack-preview">{p.items.slice(0,6).map(item=><button key={item.id} type="button" aria-label={item.title||item.label} onClick={()=>onPick(item)}><EmojiAsset entity={item} fallback={item.fallback} token={token}/></button>)}</div><button type="button" onClick={()=>preference('/v1/emoji/packs/'+p.id+'/install',p.installed?undefined:{},p.installed?'DELETE':'POST')}>{p.installed?'Удалить из моих':'Установить'}</button><button type="button" onClick={()=>{setPackId(p.id);setSection('catalog');}}>Открыть</button><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+p.url);setError('Ссылка скопирована');}catch{setError('Копирование недоступно');}}}>Ссылка</button>{p.owner?.id===userId&&!p.builtin&&<button type="button" onClick={()=>setEditingPack({id:p.id,title:p.title,description:p.description||''})}>Редактировать</button>}{editingPack?.id===p.id&&<div className="emoji-pack-edit"><label>Название<input aria-label="Изменить название набора" maxLength={64} value={editingPack.title} onChange={e=>setEditingPack({...editingPack,title:e.target.value})}/></label><label>Описание<textarea aria-label="Описание набора" maxLength={500} value={editingPack.description} onChange={e=>setEditingPack({...editingPack,description:e.target.value})}/></label><div className="emoji-pack-edit-actions"><button type="button" disabled={busy||!editingPack.title.trim()} onClick={savePack}>Сохранить</button><button type="button" onClick={()=>setEditingPack(null)}>Отмена</button></div></div>}<button type="button" onClick={()=>{const reason=window.prompt('Причина жалобы');if(reason)preference('/v1/emoji/packs/'+p.id+'/report',{reason});}}>Пожаловаться</button></article>)}{packMore&&<button type="button" disabled={busy} onClick={nextPacks}>Ещё наборы</button>}</div>:<><select aria-label="Выбрать набор эмодзи" value={packId} onChange={e=>setPackId(e.target.value)}><option value="">Все наборы</option>{packs.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><div className="custom-emoji-grid">{items.map(item=><div key={item.id}><button type="button" className="emoji-choice" aria-label={'Вставить '+item.label} onClick={()=>{onPick(item);preference('/v1/emoji/'+item.id+'/use',{});}}><EmojiAsset entity={item} token={token} fallback={item.fallback}/></button><button className="emoji-favorite" type="button" aria-label={item.favorite?'Убрать из избранных':'В избранные'} aria-pressed={!!item.favorite} onClick={()=>preference('/v1/emoji/'+item.id+'/favorite',{active:!item.favorite})}>{item.favorite?'★':'☆'}</button></div>)}</div>{more&&<button type="button" disabled={busy} onClick={next}>Показать ещё</button>}</>}
 {busy&&<p role="status">Загрузка…</p>}{!busy&&!items.length&&section!=='packs'&&!error&&<p>В этом разделе пока пусто</p>}
 <button type="button" className="emoji-create" onClick={()=>setCreating(v=>!v)}>Создать свой набор</button>
 {creating&&<div className="emoji-author"><label>Название<input aria-label="Название набора" maxLength={64} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Изображения PNG / WebP<input type="file" multiple accept="image/png,image/webp" disabled={busy} onChange={e=>{files(Array.from(e.target.files));e.target.value='';}}/></label><small>Изображения преобразуются в статичный PNG 100×100. До 200 эмодзи в наборе.</small>{assets.map((a,i)=><div className="emoji-author-item" key={a.attachment_id}><input aria-label="Название эмодзи" value={a.label} maxLength={64} onChange={e=>setAssets(xs=>xs.map((x,n)=>n===i?{...x,label:e.target.value}:x))}/><input aria-label="Unicode fallback" value={a.fallback} maxLength={32} onChange={e=>setAssets(xs=>xs.map((x,n)=>n===i?{...x,fallback:e.target.value}:x))}/><input aria-label="Ключевые слова ru en" placeholder="Ключевые слова: радость happy" value={a.keywords.join(' ')} onChange={e=>setAssets(xs=>xs.map((x,n)=>n===i?{...x,keywords:e.target.value.split(/\s+/)}:x))}/><button type="button" aria-label="Убрать файл" onClick={()=>setAssets(xs=>xs.filter((x,n)=>n!==i))}>×</button></div>)}<label><input type="checkbox" checked={own} onChange={e=>setOwn(e.target.checked)}/>Публичный набор</label><button type="button" disabled={busy||!title.trim()||!assets.length||assets.length>200} onClick={create}>Создать и установить</button></div>}
 </section>;
}
