import React,{useRef,useState,useEffect,useLayoutEffect,forwardRef,useImperativeHandle} from 'react';
import {cachedEmojiBlob} from './EmojiAsset';
import {request} from './api';
import {replaceText} from '../../shared/emoji-text.mjs';

function content(root){let text='',entities=[];function visit(node){if(node.nodeType===3){text+=node.data;return;}if(node.nodeType!==1)return;if(node.dataset?.emojiId){const fallback=node.dataset.fallback;entities.push({id:node.dataset.emojiId,start:text.length,length:fallback.length,attachment_id:node.dataset.file||undefined,mime:'image/png'});text+=fallback;return;}if(node.tagName==='BR'){if(!node.dataset.editorTail)text+='\n';return;}for(const child of node.childNodes)visit(child);}for(const child of root.childNodes)visit(child);return {text,entities};}
function pointOffset(root,node,offset){const range=document.createRange();range.selectNodeContents(root);try{range.setEnd(node,offset);}catch{return 0;}return content(range.cloneContents()).text.length;}
function selectionOffsets(root){const selection=window.getSelection();if(!selection?.rangeCount||!root.contains(selection.anchorNode)||!root.contains(selection.focusNode))return [0,0];const a=pointOffset(root,selection.anchorNode,selection.anchorOffset),b=pointOffset(root,selection.focusNode,selection.focusOffset);return [Math.min(a,b),Math.max(a,b)];}
function select(root,start,end){let offset=0,points=[];function visit(node){if(node.nodeType===3){points.push({start:offset,end:offset+node.data.length,node});offset+=node.data.length;return;}if(node.dataset?.emojiId){points.push({start:offset,end:offset+node.dataset.fallback.length,node,atomic:true});offset+=node.dataset.fallback.length;return;}for(const child of node.childNodes)visit(child);}visit(root);const locate=pos=>{for(const p of points){if(pos<=p.end){if(p.atomic){const index=[...p.node.parentNode.childNodes].indexOf(p.node);return [p.node.parentNode,index+(pos>p.start?1:0)];}return [p.node,Math.max(0,Math.min(p.node.data.length,pos-p.start))];}}return [root,root.childNodes.length];};const range=document.createRange();range.setStart(...locate(start));range.setEnd(...locate(end));const s=window.getSelection();s.removeAllRanges();s.addRange(range);}

/** Plain text plus atomic custom-emoji nodes. No pasted HTML is inserted. */
export default forwardRef(function EmojiEditor({value,entities=[],token,selection,disabled,onChange,onSelect,onKeyDown,onCopy,onCut,onPaste,...props},ref){
 const root=useRef(null),composing=useRef(false),[revision,setRevision]=useState(0),signature=JSON.stringify([value,entities,token]);useImperativeHandle(ref,()=>root.current,[]);
 useEffect(()=>{const clear=()=>setRevision(v=>v+1);window.addEventListener('volna-emoji-cache-cleared',clear);return()=>window.removeEventListener('volna-emoji-cache-cleared',clear);},[]);
 useLayoutEffect(()=>{const el=root.current;Object.defineProperties(el,{selectionStart:{configurable:true,get:()=>selectionOffsets(el)[0]},selectionEnd:{configurable:true,get:()=>selectionOffsets(el)[1]}});el.setSelectionRange=(a,b)=>select(el,a,b);return()=>{delete el.selectionStart;delete el.selectionEnd;delete el.setSelectionRange;};},[]);
 useLayoutEffect(()=>{const el=root.current;const focused=document.activeElement===el;const urls=[];let live=true,cursor=0;el.replaceChildren();for(const entity of entities){if(entity.start<cursor||entity.start+entity.length>value.length)continue;el.append(document.createTextNode(value.slice(cursor,entity.start)));const span=document.createElement('span'),fallback=value.slice(entity.start,entity.start+entity.length);span.contentEditable='false';span.className='emoji-asset emoji-inline';span.dataset.emojiId=entity.id;span.dataset.fallback=fallback;if(entity.attachment_id)span.dataset.file=entity.attachment_id;span.setAttribute('role','img');span.setAttribute('aria-label',entity.label||fallback);span.textContent=fallback;el.append(span);(async()=>{const item=entity.attachment_id?entity:await request('/v1/emoji/'+entity.id,token);if(!/^[a-f0-9]{48}$/.test(item.attachment_id||'')||item.mime&&!['image/png','image/webp'].includes(item.mime))return;const blob=await cachedEmojiBlob(item.attachment_id,token);if(!live)return;const url=URL.createObjectURL(blob);urls.push(url);span.dataset.file=item.attachment_id;const image=document.createElement('img');image.src=url;image.alt=fallback;image.dataset.emojiFallback=fallback;image.dataset.emojiId=entity.id;image.draggable=false;image.onerror=()=>{span.textContent=fallback;};span.replaceChildren(image);})().catch(()=>{});cursor=entity.start+entity.length;}el.append(document.createTextNode(value.slice(cursor)));if(value.endsWith('\n')){const tail=document.createElement('br');tail.dataset.editorTail='true';el.append(tail);}if(focused)select(el,...selection.current);return()=>{live=false;urls.forEach(URL.revokeObjectURL);};},[signature,revision]);
 function changed(){if(composing.current)return;const el=root.current,data=content(el),[a,b]=selectionOffsets(el);selection.current=[a,b];if(data.text.length>4000){setRevision(n=>n+1);return;}onChange({target:{value:data.text},entities:data.entities});}
 function inserted(text){const el=root.current,[a,b]=selectionOffsets(el),r=replaceText(value,entities,a,b,text);if(r.text.length>4000)return;selection.current=[r.caret,r.caret];onChange({target:{value:r.text},entities:r.entities});}
 return <div {...props} ref={root} role="textbox" aria-multiline="true" aria-disabled={disabled} data-placeholder={props.placeholder} contentEditable={!disabled} suppressContentEditableWarning className="emoji-editor" onCompositionStart={()=>{composing.current=true;}} onCompositionEnd={()=>{composing.current=false;changed();}} onBeforeInput={e=>{const type=e.nativeEvent.inputType;if(/^format/.test(type||'')){e.preventDefault();return;}if(!composing.current&&['insertParagraph','insertLineBreak'].includes(type)){e.preventDefault();inserted('\n');}}} onInput={changed} onKeyUp={()=>onSelect?.({target:root.current})} onPointerUp={()=>onSelect?.({target:root.current})} onKeyDown={e=>{onKeyDown(e);if(!e.defaultPrevented&&e.key==='Enter'&&!e.nativeEvent.isComposing){e.preventDefault();inserted('\n');}}} onDrop={e=>{if(e.dataTransfer.types.includes('Files'))return;e.preventDefault();inserted(e.dataTransfer.getData('text/plain'));}} onCopy={onCopy} onCut={onCut} onPaste={e=>{onPaste(e);if(!e.defaultPrevented){e.preventDefault();inserted(e.clipboardData.getData('text/plain'));}}}>{value}</div>;
});
