import React,{useState,useEffect} from 'react';
import {Icon,Avatar} from './ui';
import {normalizeFolders,defaultFolders,folderMatches,FOLDER_LIMIT,SIDEBAR_STORAGE} from './sidebar-state.mjs';
const types=[['all','Все'],['direct','Личные'],['contacts','Контакты'],['non_contacts','Не контакты'],['group','Группы'],['channel','Каналы'],['archived','Архив']];
export default function FolderSettings({chats,folders,onChange,token,busy=false,onEditing}){
 const [draft,setDraft]=useState(null),[mode,setMode]=useState('chats');
 useEffect(()=>{onEditing?.(!!draft);return()=>onEditing?.(false);},[!!draft]);
 const available=chats.filter(c=>!c.parent_id);
 function edit(f){setDraft(f?{...f}:normalizeFolders([{id:'folder-'+crypto.randomUUID(),name:'Новая папка'}])[0]);setMode('chats');}
 function patch(p){setDraft(f=>({...f,...p}));}
 function toggle(field,value){const selected=draft[field];patch({[field]:selected.includes(value)?selected.filter(x=>x!==value):[...selected,value]});}
 async function save(e){e.preventDefault();if(await onChange(folders.some(f=>f.id===draft.id)?folders.map(f=>f.id===draft.id?draft:f):[...folders,draft]))setDraft(null);}
 function move(index,delta){const next=[...folders],other=index+delta;if(other<0||other>=next.length)return;[next[index],next[other]]=[next[other],next[index]];onChange(next);}
 async function importLegacy(){let legacy=[];try{legacy=normalizeFolders(JSON.parse(localStorage.getItem(SIDEBAR_STORAGE)||'[]'));}catch{}const ids=new Set(available.map(c=>c.id));const imported=legacy.filter(f=>!folders.some(x=>x.id===f.id)).map(f=>({...f,chats:f.chats.filter(id=>ids.has(id)),excluded:f.excluded.filter(id=>ids.has(id)),pinned:f.pinned.filter(id=>ids.has(id))}));await onChange([...folders,...imported].slice(0,FOLDER_LIMIT));}
 if(draft)return <form className="folder-editor" onSubmit={save}><fieldset disabled={busy}><label>Название<input autoFocus maxLength={32} required value={draft.name} onChange={e=>patch({name:e.target.value})}/></label><label>Значок<input maxLength={12} value={draft.icon} onChange={e=>patch({icon:e.target.value})}/></label><label>Правило<select value={draft.rule} onChange={e=>patch({rule:e.target.value})}>{[['','Выбранные чаты'],...defaultFolders().map(f=>[f.rule,f.name])].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><p>Дополнительные типы чатов</p>{types.map(([id,name])=><label className="setting-check" key={id}><input type="checkbox" checked={draft.types.includes(id)} onChange={()=>toggle('types',id)}/>{name}</label>)}{[['excludeMuted','Исключить без звука'],['excludeRead','Исключить прочитанные'],['excludeArchived','Исключить архив']].map(([id,name])=><label className="setting-check" key={id}><input type="checkbox" checked={draft[id]} onChange={e=>patch({[id]:e.target.checked})}/>{name}</label>)}<p>Явно добавленные и закреплённые чаты остаются видимыми; исключения имеют приоритет.</p><div className="folder-buttons">{[['chats','Добавить'],['excluded','Исключить'],['pinned','Закрепить']].map(([id,name])=><button type="button" key={id} aria-pressed={mode===id} onClick={()=>setMode(id)}>{name}</button>)}</div><div className="folder-chat-selection">{available.map(c=><label key={c.id}><input type="checkbox" checked={draft[mode].includes(c.id)} onChange={()=>toggle(mode,c.id)}/><Avatar name={c.name} id={c.id} src={c.avatar_url} token={token}/><span>{c.name}</span></label>)}</div>{mode==='pinned'&&draft.pinned.map((id,index)=><div key={id}>{available.find(c=>c.id===id)?.name||'Чат'}<button type="button" disabled={!index} aria-label="Поднять закреплённый чат" onClick={()=>{const next=[...draft.pinned];[next[index],next[index-1]]=[next[index-1],next[index]];patch({pinned:next});}}>↑</button></div>)}<div className="folder-buttons"><button type="button" onClick={()=>setDraft(null)}>Отмена</button><button className="primary" disabled={!draft.name.trim()}>Сохранить</button></div></fieldset></form>;
 return <section className="folder-settings"><p>До {FOLDER_LIMIT} папок. Названия, правила, порядок и закрепления синхронизируются между Android, Web и Windows.</p>{folders.map((f,i)=><div className="folder-setting-row" key={f.id}><button disabled={busy} onClick={()=>edit(f)}><Icon name="chat"/><span>{f.icon}{f.name}<small>{available.filter(c=>folderMatches(f,c)).length} чатов</small></span></button><button disabled={busy||i===0} aria-label={'Поднять '+f.name} onClick={()=>move(i,-1)}>↑</button><button disabled={busy||i===folders.length-1} aria-label={'Опустить '+f.name} onClick={()=>move(i,1)}>↓</button><button disabled={busy||folders.length>=FOLDER_LIMIT} aria-label={'Копировать '+f.name} onClick={()=>onChange([...folders,{...f,id:'folder-'+crypto.randomUUID(),name:f.name.slice(0,24)+' копия'}])}>⧉</button><button disabled={busy} aria-label={'Удалить папку '+f.name} onClick={()=>onChange(folders.filter(x=>x.id!==f.id))}><Icon name="trash"/></button></div>)}<button disabled={busy||folders.length>=FOLDER_LIMIT} onClick={()=>edit(null)}>Создать папку</button><button disabled={busy} onClick={()=>onChange([...folders,...defaultFolders().filter(f=>!folders.some(x=>x.id===f.id))].slice(0,FOLDER_LIMIT))}>Добавить стандартные папки</button><button disabled={busy} onClick={importLegacy}>Импортировать локальные папки этого устройства</button><p>Удаление папки сохраняет переписки. При одновременном редактировании приложение предложит сверить изменения.</p></section>;
}
