import React,{useState} from 'react';
import {Icon,Avatar} from './ui';
export default function FolderSettings({chats,folders,onChange,token}){
 const [editing,setEditing]=useState(null),[name,setName]=useState(''),[included,setIncluded]=useState(new Set());
 function edit(folder){setEditing(folder?.id||'new');setName(folder?.name||'');setIncluded(new Set(folder?.chats||[]));}
 function save(e){e.preventDefault();const item={id:editing==='new'?'folder-'+crypto.randomUUID():editing,name:name.trim(),chats:[...included]};if(!item.name)return;onChange(editing==='new'?[...folders,item]:folders.map(f=>f.id===editing?item:f));setEditing(null);}
 if(editing)return <form className="folder-editor" onSubmit={save}><label>Название папки<input autoFocus maxLength={32} required value={name} onChange={e=>setName(e.target.value)}/></label><p>Выберите чаты для этой папки</p><div className="folder-chat-selection">{chats.filter(c=>!c.parent_id).map(c=><label key={c.id}><input type="checkbox" checked={included.has(c.id)} onChange={()=>setIncluded(prev=>{const next=new Set(prev);next.has(c.id)?next.delete(c.id):next.add(c.id);return next;})}/><Avatar name={c.name} id={c.id} src={c.avatar_url} token={token}/><span>{c.name}</span></label>)}</div><div className="folder-buttons"><button type="button" onClick={()=>setEditing(null)}>Отмена</button><button className="primary" disabled={!name.trim()}>Сохранить</button></div></form>;
 return <section className="folder-settings"><p>Папки хранятся на этом устройстве. Вы можете добавить до 12 папок; вкладки появятся над списком чатов.</p>{folders.map(f=><div className="folder-setting-row" key={f.id}><button onClick={()=>edit(f)}><Icon name="chat"/><span>{f.name}<small>{f.chats.length} чатов</small></span></button><button aria-label={'Удалить папку '+f.name} onClick={()=>onChange(folders.filter(x=>x.id!==f.id))}><Icon name="trash"/></button></div>)}<button className="settings-row" disabled={folders.length>=12} onClick={()=>edit(null)}><Icon name="plus"/>Создать папку</button></section>;
}
