import React,{useState,useEffect,useRef} from 'react';
import {request} from './api';
import {Avatar,Icon} from './ui';
import Attachment from './Attachment';
import MessageText from './MessageText';
export default function InfoPanel({chat,token,revision,onClose,onProfile,onManage,onPreference,onJump}){
 const [profile,setProfile]=useState(null),[tab,setTab]=useState('media'),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[attempt,setAttempt]=useState(0),[more,setMore]=useState(false);const root=useRef(null),requestVersion=useRef(0);
 const community=['group','channel'].includes(chat.kind),parent=chat.parent_id||chat.id;
 useEffect(()=>{const before=document.activeElement;root.current?.querySelector('button')?.focus();return()=>before?.isConnected&&before.focus();},[]);
 useEffect(()=>{const c=new AbortController();setError('');request(community?'/communities/'+parent:chat.saved?'/me':'/users/'+chat.peer_id,token,undefined,c.signal).then(setProfile).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[chat.id,token,revision,attempt]);
 useEffect(()=>{const c=new AbortController();requestVersion.current++;setBusy(true);setRows([]);setError('');request(`/chats/${chat.id}/media?type=${tab}`,token,undefined,c.signal).then(r=>{setRows(r);setMore(r.length===50);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return()=>c.abort();},[chat.id,tab,token,revision,attempt]);
 async function loadMore(){const version=requestVersion.current;setBusy(true);try{const r=await request(`/chats/${chat.id}/media?type=${tab}&before=${rows.at(-1).id}`,token);if(version!==requestVersion.current)return;setRows(a=>[...a,...r]);setMore(r.length===50);}catch(e){if(version===requestVersion.current)setError(e.message);}finally{if(version===requestVersion.current)setBusy(false);}}
 function keys(e){if(e.key==='Escape'){e.stopPropagation();onClose();}if(e.key==='Tab'&&matchMedia('(max-width:1479px)').matches){const items=[...root.current.querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),video[controls]')];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}
 return <aside className="info-panel" ref={root} role="dialog" aria-label="Информация о чате" aria-modal={matchMedia('(max-width:1479px)').matches||undefined} onKeyDown={keys}>
 <header><button className="icon-button" aria-label="Закрыть информацию" onClick={onClose}><Icon name="close"/></button><h2>{community?'Информация о сообществе':'Информация'}</h2></header>
 <div className="info-scroll"><section className="info-person"><Avatar name={chat.name} id={chat.peer_id||chat.id} src={profile?.avatar_url||chat.avatar_url} token={token}/><h2>{chat.name}</h2><p>{community?`${chat.member_count} участников`:chat.saved?'Сохранённые сообщения':profile?.online?'В сети':'Был(а) недавно'}</p></section>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>setAttempt(v=>v+1)}>Повторить</button></div>}
 <div className="info-facts">{profile?.username&&<a href={profile.profile_url||'/'+profile.username} target="_blank" rel="noreferrer"><strong>@{profile.username}</strong><small>Имя пользователя</small></a>}{profile?.phone&&<div><strong>{profile.phone}</strong><small>Телефон</small></div>}{(profile?.bio||profile?.description)&&<div><p>{profile.bio||profile.description}</p><small>О себе</small></div>}
 <label className="info-notifications"><span><Icon name="bell"/>Уведомления</span><input type="checkbox" checked={!chat.muted} onChange={()=>onPreference(chat,{muted:!chat.muted})}/></label>
 {community?<button className="info-action" onClick={onManage}><Icon name="group"/>Участники и управление</button>:<button className="info-action" onClick={()=>onProfile(profile?.id||chat.peer_id)}><Icon name="edit"/>Открыть профиль</button>}
 </div>{community&&profile?.members?.length>0&&<details className="info-members"><summary>Участники · {profile.members.length}</summary>{profile.members.map(p=><button key={p.id} onClick={()=>onProfile(p.id)}><Avatar name={p.name} id={p.id}/><span>{p.name}<small>{p.role==='owner'?'Владелец':p.role==='admin'?'Администратор':'@'+p.username}</small></span></button>)}</details>}
 <div className="info-tabs" role="tablist" aria-label="Вложения чата">{[['media','Медиа'],['files','Файлы'],['links','Ссылки'],['voice','Голос']].map(([k,label])=><button role="tab" aria-selected={tab===k} key={k} onClick={()=>setTab(k)}>{label}</button>)}</div>
 <div className={'info-content '+(tab==='media'?'info-media-grid':'')}>{rows.map(m=><div key={m.id} className="info-item">{m.attachment?<Attachment file={m.attachment} token={token} messageId={m.id} transcript={m.transcript||''} gallery={rows.filter(r=>r.attachment?.mime.startsWith('image/')).map(r=>r.attachment)}/>:<MessageText text={m.text}/>}<button className="info-jump" onClick={()=>onJump(m)} aria-label="Перейти к сообщению">{new Date(m.created_at).toLocaleDateString('ru-RU')} <Icon name="reply"/></button></div>)}</div>
 {busy&&<p className="history-note" role="status">Загрузка…</p>}{!busy&&!rows.length&&!error&&<p className="history-note">Пока нет {tab==='media'?'фото и видео':tab==='files'?'документов':tab==='links'?'ссылок':'голосовых сообщений'}</p>}{more&&<button className="load-more" disabled={busy} onClick={loadMore}>Показать ещё</button>}
 </div></aside>;
}
