import {useEffect,useRef} from 'react';
export const reactions=['👍','❤️','😂','🔥','🎉','😢','👏','😍','🤔','😮','🙏','💯','👎','🥰','🤣','😎','😭','🤝','💪','👋','✨','💙','😡','🤗'];
export function groupMessages(messages){const groups=[];for(const m of messages){const last=groups.at(-1);if(m.album_id&&last?.[0].album_id===m.album_id&&last[0].sender_id===m.sender_id)last.push(m);else groups.push([m]);}return groups;}
export function useMessageGestures(){
 const timer=useRef(null),point=useRef(null),held=useRef(false);const cancel=()=>{clearTimeout(timer.current);point.current=null;};
 useEffect(()=>{const outside=e=>{document.querySelectorAll('.message-actions[open],.chat-actions[open],.app-menu[open]').forEach(d=>{if(!d.contains(e.target))d.open=false;});};const key=e=>{const menu=e.target.closest('.message-menu,.app-menu-content,.chat-actions[open]>div');if(menu&&['ArrowDown','ArrowUp','Home','End'].includes(e.key)){const nodes=[...menu.querySelectorAll('button:not(:disabled),a[href]')].filter(n=>n.getClientRects().length);const i=nodes.indexOf(document.activeElement);if(nodes.length){e.preventDefault();nodes[e.key==='Home'?0:e.key==='End'?nodes.length-1:(i+(e.key==='ArrowDown'?1:-1)+nodes.length)%nodes.length].focus();}}if(e.key==='Escape')document.querySelectorAll('details[open]').forEach(d=>d.open=false);};const scroll=e=>{if(e.target.classList?.contains('messages'))document.querySelectorAll('.message-actions[open]').forEach(d=>d.open=false);};document.addEventListener('scroll',scroll,true);document.addEventListener('pointerdown',outside);document.addEventListener('keydown',key);return()=>{document.removeEventListener('scroll',scroll,true);cancel();document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',key);};},[]);
 const open=(article,x,y)=>{const d=article.querySelector('.message-actions');if(d){d.dataset.menuX=String(x??'');d.dataset.menuY=String(y??'');d.open=true;requestAnimationFrame(()=>d.querySelector('.message-menu button')?.focus());}};
 return {onContextMenu:e=>{if(e.target.closest('input,textarea,video,a'))return;e.preventDefault();open(e.currentTarget,e.clientX,e.clientY);},onClickCapture:e=>{if(held.current){e.preventDefault();e.stopPropagation();held.current=false;}},onPointerDown:e=>{held.current=false;const control=e.target.closest('button,input,video,a,summary,details');if(e.pointerType!=='touch'||(control&&!control.classList.contains('image-open')))return;cancel();const target=e.currentTarget;point.current=[e.clientX,e.clientY];timer.current=setTimeout(()=>{point.current=null;held.current=true;open(target);},520);},onPointerMove:e=>{if(point.current&&Math.hypot(e.clientX-point.current[0],e.clientY-point.current[1])>8)cancel();},onPointerUp:cancel,onPointerCancel:cancel};
}
export function positionMessageMenu(event){const d=event.currentTarget;if(!d.open)return;const menu=d.querySelector('.message-menu');if(!menu)return;const anchor=d.getBoundingClientRect(),hasPoint=d.dataset.menuX&&d.dataset.menuY,r=hasPoint?{right:Number(d.dataset.menuX),top:Number(d.dataset.menuY),bottom:Number(d.dataset.menuY)}:anchor;delete d.dataset.menuX;delete d.dataset.menuY;const width=Math.min(216,innerWidth-16),below=innerHeight-r.bottom-12,above=r.top-12,up=below<Math.min(menu.scrollHeight,300)&&above>below;Object.assign(menu.style,{position:'fixed',width:width+'px',left:Math.max(8,Math.min(innerWidth-width-8,r.right-width))+'px',top:up?'auto':(r.bottom+5)+'px',bottom:up?(innerHeight-r.top+5)+'px':'auto',maxHeight:Math.max(70,up?above:below)+'px'});}
