import React,{useEffect,useState} from 'react';
import DesktopNotifications from './DesktopNotifications';
import {Capacitor} from '@capacitor/core';
import {request} from './api';
import Dialog from './Dialog';
import {DEMO_TOKEN} from './demo-api.mjs';
function keyBytes(value){return Uint8Array.from(atob(value.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-value.length%4)%4)),c=>c.charCodeAt(0));}
export default function Notifications(props){if(props.token===DEMO_TOKEN)return <DemoNotifications onClose={props.onClose}/>;return window.volnaDesktop?<DesktopNotifications {...props}/>:<WebNotifications {...props}/>;}
function WebNotifications({token,onClose}){
 const [enabled,setEnabled]=useState(false),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false);
 const supported=window.isSecureContext&&'serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window&&!Capacitor.isNativePlatform()&&(location.protocol==='https:'||location.hostname==='localhost');
 async function registration(){const r=await navigator.serviceWorker.register('/sw.js',{updateViaCache:'none'});await r.update();await navigator.serviceWorker.ready;return r;}
 useEffect(()=>{let stopped=false;(async()=>{if(!supported){setLoaded(true);return;}try{const r=await registration(),sub=await r.pushManager.getSubscription();if(sub){const state=await request('/push/status',token,{endpoint:sub.endpoint});if(!stopped){setEnabled(state.subscribed&&Notification.permission==='granted');setPreview(state.preview);}}}catch(e){if(!stopped)setError(e.message);}finally{if(!stopped)setLoaded(true);}})();return()=>{stopped=true;};},[token,supported]);
 async function enable(){setBusy(true);setError('');try{
  if(await Notification.requestPermission()!=='granted')throw Error('Разрешите уведомления для Волны в настройках браузера и Android.');
  const [r,config]=await Promise.all([registration(),request('/push/config',token)]);let sub=await r.pushManager.getSubscription();
  if(!sub)sub=await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes(config.publicKey)});
  try{await request('/push/subscribe',token,{subscription:sub.toJSON(),preview});}catch(e){if(e.status!==409)throw e;await sub.unsubscribe();sub=await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes(config.publicKey)});await request('/push/subscribe',token,{subscription:sub.toJSON(),preview});}
  setEnabled(true);
 }catch(e){setError(e.message||'Не удалось включить уведомления');}finally{setBusy(false);}}
 async function disable(){setBusy(true);setError('');try{const r=await registration(),sub=await r.pushManager.getSubscription();if(sub){await request('/push/unsubscribe',token,{endpoint:sub.endpoint});await sub.unsubscribe();}for(const n of await r.getNotifications())n.close();setEnabled(false);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="modal-backdrop"><section className="modal notification-settings" role="dialog" aria-modal="true" aria-label="Уведомления"><header><h2>Уведомления</h2><button autoFocus disabled={busy} aria-label="Закрыть уведомления" onClick={onClose}>×</button></header>{supported?<><p>Получайте сообщения, даже когда экран телефона погашен или окно Волны закрыто.</p><p className="notification-state">{loaded?(enabled?'Включены на этом устройстве':'Выключены на этом устройстве'):'Проверяем…'}</p><label><input type="checkbox" checked={preview} disabled={busy} onChange={e=>setPreview(e.target.checked)}/> Показывать имя и текст сообщения</label><small>Без этого флажка на экране блокировки будет только «Волна — Новое сообщение». Изменение применяется кнопкой ниже.</small><button className="primary" disabled={busy||!loaded} onClick={enable}>{busy?'Подождите…':enabled?'Сохранить настройки':'Включить уведомления'}</button>{enabled&&<button disabled={busy} onClick={disable}>Выключить на этом устройстве</button>}<p>На Android установите Волну через Chrome и разрешите системные уведомления. Не останавливайте Chrome принудительно. Энергосбережение и «Не беспокоить» могут задерживать или заглушать уведомления.</p><p>Подписка действует до выхода из аккаунта или окончания входа (7 дней). После повторного входа откройте этот раздел и включите её снова.</p></>:<p>В этом клиенте Web Push недоступен. На Android откройте Волну в Chrome и установите её на главный экран. Для отдельного APK потребуется настройка Firebase; в эту сборку она не входит.</p>}{error&&<p role="alert" className="error">{error}</p>}</section></div>;
}

function DemoNotifications({onClose}){const [enabled,setEnabled]=useState(()=>{try{return localStorage.getItem('volna.demo.notifications')!=='off';}catch{return true;}}),[sound,setSound]=useState(()=>{try{return localStorage.getItem('volna.demo.sound')!=='off';}catch{return true;}});return <Dialog title="Уведомления · Демо" onClose={onClose}><label className="setting-check"><input type="checkbox" checked={enabled} onChange={e=>{setEnabled(e.target.checked);try{localStorage.setItem('volna.demo.notifications',e.target.checked?'on':'off');}catch{}}}/>Показывать уведомления в демо</label><label className="setting-check"><input type="checkbox" checked={sound} onChange={e=>{setSound(e.target.checked);try{localStorage.setItem('volna.demo.sound',e.target.checked?'on':'off');}catch{}}}/>Звук уведомлений</label><p>Локальные настройки демонстрации. Уведомления каждого чата настраиваются в его информационной панели.</p></Dialog>;}
