import React,{useEffect,useState} from 'react';
import {API,request} from './api';
import {qrSvgPath} from './qr-code.mjs';
export default function PhoneQrLogin({onSession}){
 const [attempt,setAttempt]=useState(0),[qr,setQr]=useState(null),[status,setStatus]=useState('pending'),[error,setError]=useState(''),[remaining,setRemaining]=useState(180);
 useEffect(()=>{const controller=new AbortController();let timeout;setQr(null);setError('');setStatus('pending');
 (async()=>{try{const value=await request('/auth/qr/request','',{platform:window.volnaDesktop?'windows':'web'},controller.signal);if(controller.signal.aborted)return;value.deadline=Date.now()+value.expires_in*1000;setQr(value);
 const poll=async()=>{try{const result=await request('/auth/qr/poll','',{id:value.id,poll_token:value.poll_token},controller.signal);if(controller.signal.aborted)return;setStatus(result.status);if(result.token){await onSession(result);return;}if(['expired','rejected','used'].includes(result.status))return;timeout=setTimeout(poll,2000);}catch(e){if(!controller.signal.aborted){setError(e.message);timeout=setTimeout(poll,3000);}}};await poll();
 }catch(e){if(!controller.signal.aborted)setError(e.message);}})();return()=>{controller.abort();clearTimeout(timeout);};},[attempt,onSession]);
 useEffect(()=>{if(!qr)return;const tick=()=>setRemaining(Math.max(0,Math.ceil((qr.deadline-Date.now())/1000)));tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer);},[qr]);
 return <main className="auth"><section className="auth-card qr-login"><span className="eyebrow">ВОЛНА · {window.volnaDesktop?'WINDOWS':'WEB'}</span><h1>Вход по QR</h1><p>Откройте Android-приложение и отсканируйте QR-код для входа.</p><div className="login-qr">{qr&&remaining>0&&!['rejected','expired','used'].includes(status)?<svg viewBox="0 0 45 45" role="img" aria-label="QR-код входа Волны" shapeRendering="crispEdges"><rect width="45" height="45" fill="white"/><path d={qrSvgPath(qr.qr_text)} fill="#101820"/></svg>:<span>{qr?'QR-код больше не действует':'Готовим QR…'}</span>}</div><p role="status">{status==='scanned'?'Подтвердите вход на телефоне':status==='rejected'?'Вход отклонён на телефоне':remaining===0||status==='expired'?'Время действия истекло':`Код действует ${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`}</p>{error&&<p role="alert" className="error">{error}</p>}<button className="secondary" onClick={()=>setAttempt(x=>x+1)}>Обновить QR</button><a href={API+"/download/volna-android.apk"}>Скачать Android</a><a href={API+"/"}>О проекте</a><a className="demo-entry" href="/app?demo=1">Посмотреть интерфейс · Демо</a><small>Настройки → Безопасность → Сканировать QR. Подтверждайте только вход на своём устройстве.</small></section></main>;
}
