import React,{useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Icon} from './ui';
export default function PinBanner({pins,onJump,onUnpin}){
 const [selected,setSelected]=useState(null),[busy,setBusy]=useState(false),[pending,setPending]=useState(null);
 const dialog=useRef(null);
 useEffect(()=>{if(!pending)return;dialog.current?.querySelector('button')?.focus();const key=e=>{if(e.key==='Escape'){e.preventDefault();if(!busy)setPending(null);}if(e.key==='Tab'){const buttons=[...dialog.current.querySelectorAll('button:not(:disabled)')];if(!buttons.length){e.preventDefault();return;}const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);requestAnimationFrame(()=>{if(!document.querySelector('.unpin-dialog'))document.querySelector('.composer [role="textbox"]')?.focus({preventScroll:true});});};},[pending,busy]);
 const pinIds=pins.map(m=>m.id).join(',');
 useEffect(()=>{setSelected(null);},[pinIds]);
 if(!pins.length)return null;
 const index=Math.max(0,pins.findIndex(m=>m.id===selected)),message=pins[index];
 const preview=message.text||message.poll?.question||(message.attachment?.mime?.startsWith('audio/')?'Голосовое сообщение':message.attachment?.name)||'Сообщение';
 async function open(){if(busy)return;setBusy(true);try{if(await onJump(message)!==false)setSelected(pins[(index+1)%pins.length].id);}finally{setBusy(false);}}
 return <><div className="pin-banner" role="region" aria-label="Закреплённое сообщение"><button type="button" className="pin-banner-jump" aria-label="Перейти к закреплённому сообщению" disabled={busy} onClick={open}><Icon name="pin"/><span className="pin-banner-marker" aria-hidden="true">{pins.slice(0,5).map((m,i)=><i key={m.id} className={i===index%5?'active':''}/>)}</span><span className="pin-banner-copy"><strong>Закреплённое сообщение{pins.length>1?' #'+(pins.length-index):''}</strong><span>{preview}</span></span></button><button type="button" className="pin-banner-close icon-button" aria-label="Открепить сообщение" disabled={busy} onClick={()=>setPending(message)}><Icon name="close"/></button></div>{pending&&createPortal(<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget&&!busy)setPending(null);}}><section ref={dialog} role="dialog" aria-modal="true" aria-label="Открепить сообщение" className="modal unpin-dialog"><header><span className="unpin-dialog-icon"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M7 3h10a2 2 0 0 1 2 2v16l-7-4-7 4V5a2 2 0 0 1 2-2Z"/></svg></span><h2>Открепить сообщение</h2></header><p>Хотите открепить это сообщение?</p><footer><button type="button" disabled={busy} onClick={()=>setPending(null)}>Отмена</button><button type="button" className="danger" disabled={busy} onClick={async()=>{setBusy(true);try{await onUnpin(pending);setPending(null);}finally{setBusy(false);}}}>Открепить</button></footer></section></div>,document.body)}</>;
}
