import React,{useState,useEffect,useRef} from 'react';
import {createPortal} from 'react-dom';
import Dialog from './Dialog';
import {Avatar,Icon} from './ui';
import {filterChats,dateLabel} from './chat-layout.mjs';
import {CHAT_ROW_HEIGHT,SIDEBAR_STORAGE,normalizeFolders,chatsInFolder} from './sidebar-state.mjs';
import InstallApp from './InstallApp';
import Appearance,{appearancePages} from './Appearance';
import {formatTime} from './appearance.mjs';
import FolderSettings from './FolderSettings';
const time=formatTime;
export function ChatListItem({chat:c,active,draft,token,onSelect,onPreference,timeFormat}){
 const menu=useRef(null),anchor=useRef(null);
 function position(e){if(!e.currentTarget.open)return;const content=e.currentTarget.querySelector('.chat-actions-content'),rect=e.currentTarget.getBoundingClientRect(),point=anchor.current||{x:rect.left,y:rect.bottom};anchor.current=null;const width=content.offsetWidth,height=content.offsetHeight;content.style.left=Math.max(8,Math.min(point.x,innerWidth-width-8))+'px';content.style.top=Math.max(8,Math.min(point.y,innerHeight-height-8))+'px';}
 function preference(p){menu.current.open=false;onPreference(c,p);}
 return <div className={'chat-row-wrap '+(active===c.id?'active':'')+(c.muted?' muted':'')} onContextMenu={e=>{e.preventDefault();anchor.current={x:e.clientX,y:e.clientY};menu.current.open=true;}}><button aria-current={active===c.id?'page':undefined} className={'chat-row '+(active===c.id?'active':'')} onClick={()=>onSelect(c.id)}><Avatar name={c.saved?'☆':c.name} id={c.peer_id||c.id} src={c.avatar_url} token={token}/><div className="chat-copy"><div><strong>{['group','channel'].includes(c.kind)&&<Icon name={c.kind==='group'?'group':'channel'}/>} {c.name}</strong><time>{time(c.last_at,timeFormat)}</time></div><div><p>{draft?.text?.trim()&&!draft?.edit?<><span className="draft-label">Черновик: </span>{draft.text}</>:c.last_text||'Начните разговор'}</p><span className="chat-indicators">{c.muted&&<Icon name="bellOff"/>}{c.unread>0?<span className="badge">{c.unread>999?'999+':c.unread}</span>:c.pinned&&<Icon name="pin"/>}</span></div></div></button><details ref={menu} className="chat-actions" onToggle={position} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();menu.current.open=false;menu.current.querySelector('summary')?.focus();}}}><summary aria-label={'Настройки чата '+c.name}><Icon name="more"/></summary><div className="chat-actions-content">{[[{pinned:!c.pinned},c.pinned?'Открепить чат':'Закрепить сверху','pin'],[{muted:!c.muted},c.muted?'Включить уведомления':'Отключить уведомления',c.muted?'bell':'bellOff'],[{archived:!c.archived},c.archived?'Вернуть из архива':'В архив','archive']].map(([p,label,icon])=><button key={label} onClick={()=>preference(p)}><Icon name={icon}/>{label}</button>)}</div></details></div>;
}
export default function Sidebar({chats,active,query,setQuery,filter,setFilter,people,searchMessages,searchBusy,searchError,searchMore,onSearchMore,onSearchResult,drafts,me,token,online,version,onSelect,onPreference,onStart,onProfile,onAppearance,onNotifications,onCreate,onJoin,onSaved,onLogout,onData,onTheme,demo,appearance,onAppearanceChange,appearanceSaveError}){
 const desktop=!!window.volnaDesktop,rowHeight=desktop?62:CHAT_ROW_HEIGHT;
 const [scrollTop,setScrollTop]=useState(0),list=useRef(null),searchInput=useRef(null),[screen,setScreen]=useState('chats'),[appearancePage,setAppearancePage]=useState('main'),[searchTab,setSearchTab]=useState('all'),[folders,setFolders]=useState(()=>{try{return normalizeFolders(JSON.parse(localStorage.getItem(SIDEBAR_STORAGE)||'[]'));}catch{return [];}}),[folderId,setFolderId]=useState(''),[folderError,setFolderError]=useState('');
 useEffect(()=>{if(list.current)list.current.scrollTop=0;setScrollTop(0);},[filter,query,folderId,searchTab]);
 useEffect(()=>{const close=e=>{document.querySelectorAll('.sidebar details[open]').forEach(d=>{if(!d.contains(e.target))d.open=false;});};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close);},[]);
 function changeFolders(items){const normalized=normalizeFolders(items);setFolders(normalized);if(!normalized.some(f=>f.id===folderId))setFolderId('');try{localStorage.setItem(SIDEBAR_STORAGE,JSON.stringify(normalized));setFolderError('');}catch{setFolderError('Хранилище недоступно. Папки действуют до перезагрузки.');}}
 function back(){if(screen==='appearance'&&appearancePage!=='main'){setAppearancePage(appearancePage==='color'?'background':'main');return;}if(screen==='appearance'||screen==='folders')setScreen('settings');else{setQuery('');setScreen('chats');}}
 function keys(e){if(e.key==='Escape'&&screen!=='chats'){e.stopPropagation();back();}}
 useEffect(()=>window.volnaDesktop?.onShortcut?.(shortcut=>{if(document.querySelector('[role="dialog"]'))return;if(shortcut==='search'||shortcut==='chat-search'&&!active){setQuery('');setScreen('search');requestAnimationFrame(()=>searchInput.current?.focus());}if(shortcut==='settings')setScreen('settings');}),[active]);
 const searching=screen==='search'||!!query.trim(),shown=chatsInFolder(filterChats(chats,filter,query,!!folderId&&!searching),folders,searching?'':folderId),virtual=!searching&&shown.length>80,start=virtual?Math.max(0,Math.floor((scrollTop-58)/rowHeight)-8):0,end=virtual?Math.min(shown.length,start+36):shown.length;
 const menuAction=fn=>e=>{e.currentTarget.closest('details').open=false;e.currentTarget.closest('.main-menu')?.removeAttribute('open');fn();},openSearch=()=>{setScreen('search');requestAnimationFrame(()=>searchInput.current?.focus());};
 const rows=shown.slice(start,end).map(c=><ChatListItem key={c.id} chat={c} active={active} draft={drafts[c.id]} token={token} timeFormat={appearance?.timeFormat} onSelect={id=>{onSelect(id);if(searching){setQuery('');setScreen('chats');}}} onPreference={onPreference}/>);
 const settingsActions=[['edit','Редактировать профиль',()=>onProfile(me?.id)],['settings','Внешний вид',()=>appearance?setScreen('appearance'):onAppearance()],['chat','Папки чатов',()=>setScreen('folders')],['bell','Уведомления',onNotifications],['archive','Данные и хранилище',onData]];
 const settingsView=['settings','appearance','folders'].includes(screen)?<aside className="sidebar settings-sidebar" onKeyDown={keys}><header className="sidebar-page-head"><button className="icon-button" aria-label={screen==='appearance'&&appearancePage!=='main'?'Назад к '+(appearancePage==='color'?'фонам':'внешнему виду'):screen==='settings'?'Назад к чатам':'Назад к настройкам'} onClick={back}><Icon name="back"/></button><h2>{screen==='settings'?'Настройки':screen==='appearance'?appearancePages[appearancePage]:'Папки чатов'}</h2></header><div className="sidebar-page-scroll">{screen==='settings'?<><button className="settings-account" onClick={()=>onProfile(me?.id)}><Avatar name={me?.name} id={me?.id} src={me?.avatar_url} token={token}/><strong>{me?.name}</strong><small>{me?.username?'@'+me.username:me?.phone}</small></button>{settingsActions.map(([icon,label,fn])=><button key={label} className="settings-row" onClick={fn}><Icon name={icon}/>{label}</button>)}<div className="settings-divider"/><button className="settings-row" onClick={onTheme}><Icon name="moon"/>Переключить тему</button><InstallApp/><button className="settings-row danger" onClick={onLogout}><Icon name="logout"/>{demo?'Выйти из демо':'Выйти'}</button><p className="settings-version">Волна {version} · {demo?'Демонстрация':online?'На связи':'Переподключение…'}</p></>:screen==='appearance'?<Appearance inline page={appearancePage} onNavigate={setAppearancePage} settings={appearance} onChange={onAppearanceChange} saveError={appearanceSaveError}/>:<><FolderSettings chats={chats} folders={folders} onChange={changeFolders} token={token}/>{folderError&&<p role="alert" className="error">{folderError}</p>}</>}</div></aside>:null;
 if(settingsView&&!desktop)return settingsView;
 return <><aside className={'sidebar '+(searching?'search-sidebar':'')} onKeyDown={keys}><header className="sidebar-head">{searching?<button className="icon-button sidebar-search-back" aria-label="Закрыть поиск" onClick={()=>{setQuery('');setScreen('chats');}}><Icon name="back"/></button>:<details className="app-menu main-menu"><summary aria-label="Настройки и действия"><Icon name="menu"/></summary>{desktop&&<button type="button" className="desktop-menu-backdrop" aria-label="Закрыть главное меню" onClick={e=>{e.currentTarget.closest('details').open=false;}}/>}<div className="app-menu-content"><button className="menu-account" onClick={menuAction(()=>onProfile(me?.id))}><Avatar name={me?.name} id={me?.id} src={me?.avatar_url} token={token}/><span><strong>{me?.name}</strong><small>{demo?'Локальная демонстрация':online?'На связи':'Переподключение…'}</small></span></button><hr/><button onClick={menuAction(onSaved)}><Icon name="star"/>Избранное</button><button onClick={menuAction(()=>{setQuery('');setFolderId('');setFilter('archived');})}><Icon name="archive"/>Архив</button><button onClick={menuAction(openSearch)}><Icon name="group"/>Контакты</button><hr/><button onClick={menuAction(()=>setScreen('settings'))}><Icon name="settings"/>Настройки</button><details className="main-menu-more"><summary aria-label="Ещё"><Icon name="more"/>Ещё<Icon name="down"/></summary><div><button onClick={menuAction(onTheme)}><Icon name="moon"/>{appearance?.theme==='light'?'Тёмный режим':'Светлый режим'}</button>{appearance&&<button onClick={menuAction(()=>onAppearanceChange({...appearance,animations:!appearance.animations}))}><Icon name="bellOff"/>{appearance.animations?'Без анимации':'Включить анимацию'}</button>}<hr/><button onClick={menuAction(()=>{setQuery('');setFolderId('');setFilter('unread');})}><Icon name="check"/>Непрочитанные</button><button onClick={menuAction(onCreate)}><Icon name="group"/>Создать группу / канал</button><button onClick={menuAction(onJoin)}><Icon name="plus"/>Войти по приглашению</button><button onClick={menuAction(()=>appearance?setScreen('appearance'):onAppearance())}><Icon name="settings"/>Внешний вид</button><button onClick={menuAction(onLogout)}><Icon name="logout"/>{demo?'Выйти из демо':'Выйти'}</button></div></details><small className="menu-version">Волна {version}</small></div></details>}<div className="search"><Icon name="search"/><input ref={searchInput} aria-label="Поиск пользователей и чатов" value={query} onFocus={()=>setScreen('search')} onChange={e=>setQuery(e.target.value)} placeholder="Поиск"/>{query&&<button onClick={()=>setQuery('')} aria-label="Очистить поиск"><Icon name="close"/></button>}</div></header>
 {searching?<div className="chat-filters search-tabs" role="tablist" aria-label="Результаты поиска">{[['all','Все'],['chats','Чаты'],['messages','Сообщения'],['people','Люди']].map(([key,label])=><button key={key} role="tab" aria-selected={searchTab===key} className={searchTab===key?'selected':''} onClick={()=>setSearchTab(key)}>{label}</button>)}</div>:folders.length>0&&<div className="chat-filters" role="tablist" aria-label="Папки чатов"><button role="tab" aria-selected={!folderId} className={!folderId?'selected':''} onClick={()=>{setFolderId('');setFilter('all');}}>Все чаты</button>{folders.map(f=><button key={f.id} role="tab" aria-selected={folderId===f.id} className={folderId===f.id?'selected':''} onClick={()=>{setFolderId(f.id);setFilter('all');}}>{f.name}</button>)}</div>}
 <nav ref={list} className="chat-list" aria-label={searching?'Результаты поиска':'Чаты'} onScroll={e=>setScrollTop(e.currentTarget.scrollTop)}>{!searching&&<>{filter==='archived'?<button className="archive-entry" onClick={()=>setFilter('all')}><Icon name="back"/>Архив · Назад</button>:!folderId&&chats.some(c=>c.archived)&&<button className="archive-entry" onClick={()=>setFilter('archived')}><Icon name="archive"/>Архив<span>{chats.filter(c=>!c.parent_id&&c.archived).length}</span></button>}{virtual&&start>0&&<div aria-hidden="true" style={{height:start*rowHeight}}/>}{rows}{virtual&&end<shown.length&&<div aria-hidden="true" style={{height:(shown.length-end)*rowHeight}}/>}{!shown.length&&<div className="filter-empty"><Icon name={filter==='archived'?'archive':'chat'}/><strong>{folderId?'В этой папке пока нет чатов':filter==='archived'?'Архив пуст':filter==='unread'?'Всё прочитано':'Здесь пока нет чатов'}</strong><small>Найдите человека по имени, телефону или @username</small></div>}</>}
 {searching&&(query.trim()?<>{['all','chats'].includes(searchTab)&&<><div className="section-label">ЧАТЫ</div>{rows}</>}{query.trim().length>=2&&<>{['all','people'].includes(searchTab)&&<><div className="section-label">ПОЛЬЗОВАТЕЛИ</div>{people.map(p=><button key={p.id} className="chat-row" onClick={()=>{onStart(p);setQuery('');setScreen('chats');}}><Avatar name={p.name} id={p.id} src={p.avatar_url} token={token}/><div className="chat-copy"><strong>{p.name}</strong><p>@{p.username}</p></div></button>)}</>}{['all','messages'].includes(searchTab)&&<><div className="section-label">СООБЩЕНИЯ</div>{searchMessages.map(m=><button key={m.id} className="global-search-result" onClick={()=>onSearchResult(m)}><strong>{chats.find(c=>c.id===m.chat_id)?.name||m.sender_name}</strong><p>{m.text||m.attachment?.name}</p><small>{dateLabel(m.created_at)} · {time(m.created_at,appearance?.timeFormat)}</small></button>)}{searchMore&&<button className="load-more" disabled={searchBusy} onClick={onSearchMore}>Ещё результаты</button>}</>}{searchError&&<p className="error" role="alert">{searchError}</p>}{searchBusy&&<p className="history-note" role="status">Поиск…</p>}{!searchBusy&&!searchError&&!shown.length&&!people.length&&!searchMessages.length&&<p className="empty-small">Ничего не найдено</p>}</>}</>:<p className="search-instructions">Поиск по чатам, людям и сообщениям</p>)}
 </nav></aside>{desktop&&settingsView&&createPortal(<Dialog title="Настройки" className="desktop-settings-dialog" onClose={()=>setScreen('chats')}>{settingsView}</Dialog>,document.body)}</>;
}
