import React,{useEffect,useState,useCallback} from 'react';import {request,messageId} from './api';import Dialog from './Dialog';
export default function Topics({group,token,revision,onSelect,onClose,onChanged}){
 const [info,setInfo]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[editor,setEditor]=useState(null),[name,setName]=useState(''),[description,setDescription]=useState(''),[icon,setIcon]=useState(''),[creation,setCreation]=useState(messageId),[confirm,setConfirm]=useState(null);
 const load=useCallback(()=>request(`/groups/${group.id}/topics`,token).then(setInfo).catch(e=>setError(e.message)),[group.id,token]);useEffect(()=>{load();},[load,revision]);
 const admin=['owner','admin'].includes(info?.role||group.role);
 async function act(path,data,method){setBusy(true);setError('');try{await request(`/groups/${group.id}/topics`+path,token,data,undefined,method);await load();await onChanged();return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
 function edit(topic){setEditor(topic||{});setName(topic?.name||'');setDescription(topic?.description||'');setIcon(topic?.icon||'');setCreation(messageId());}
 async function save(e){e.preventDefault();const ok=await act(editor.id?'/'+editor.id:'',{name,description,icon,...(!editor.id?{client_id:creation}:{})},editor.id?'PATCH':'POST');if(ok)setEditor(null);}
 return <Dialog title={'Подтемы · '+group.name} onClose={onClose}>{error&&<p role="alert" className="error">{error}</p>}{info&&<>
 <button className="topic-row" onClick={()=>onSelect(group.id)}>Общий чат</button>
 {admin&&<label>Кто может создавать подтемы<select value={info.create_policy} disabled={busy} onChange={e=>act('/settings',{create_policy:e.target.value})}><option value="owner">Только владелец</option><option value="admins">Владелец и администраторы</option><option value="all">Все участники</option></select></label>}
 {info.topics.map(topic=><section key={topic.id} className="topic-card"><button className="topic-row" onClick={()=>onSelect(topic.chat_id)}><span>{topic.icon||'#'}</span><strong>{topic.name}</strong>{topic.closed&&<small>Закрыта</small>}{topic.unread_count>0&&<b className="unread">{topic.unread_count}</b>}</button>{topic.description&&<p>{topic.description}</p>}<label>Уведомления<select value={topic.notification_mode} disabled={busy} onChange={e=>act('/'+topic.id+'/notifications',{mode:e.target.value})}><option value="all">Все сообщения</option><option value="mentions">Только упоминания</option><option value="none">Без уведомлений</option></select></label>{topic.can_manage&&<details><summary>Действия</summary><button disabled={busy} onClick={()=>edit(topic)}>Изменить</button><button disabled={busy} onClick={()=>act('/'+topic.id,{closed:!topic.closed},'PATCH')}>{topic.closed?'Открыть':'Закрыть'} подтему</button><button className="danger" disabled={busy} onClick={()=>setConfirm(topic)}>Удалить подтему</button></details>}</section>)}
 {info.can_create&&!editor&&<button className="primary" onClick={()=>edit(null)}>Создать подтему</button>}
 {editor&&<form onSubmit={save}><h3>{editor.id?'Изменить':'Создать'} подтему</h3><label>Название<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} disabled={busy}/></label><label>Описание<textarea maxLength={1000} value={description} onChange={e=>setDescription(e.target.value)} disabled={busy}/></label><label>Иконка / эмодзи<input maxLength={16} value={icon} onChange={e=>setIcon(e.target.value)} disabled={busy}/></label><button className="primary" disabled={busy}>Сохранить</button><button type="button" disabled={busy} onClick={()=>setEditor(null)}>Отмена</button></form>}
 {confirm&&<section role="alertdialog"><p>Удалить «{confirm.name}» и её историю у всех участников?</p><button className="danger" disabled={busy} onClick={async()=>{if(await act('/'+confirm.id,undefined,'DELETE'))setConfirm(null);}}>Удалить</button><button disabled={busy} onClick={()=>setConfirm(null)}>Отмена</button></section>}
 </>}</Dialog>;
}
