const {chromium}=require('playwright');
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const root=path.resolve(__dirname,'..');const uploadDir=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'volna-ui-'));const {createApp}=await import('../server/index.mjs');const api=createApp({database:':memory:',uploads:uploadDir});await new Promise(r=>api.server.listen(3000,'127.0.0.1',r));
 const web=http.createServer((req,res)=>{if(req.url.startsWith('/api/')){const proxy=http.request({hostname:'127.0.0.1',port:3000,path:req.url,method:req.method,headers:req.headers},up=>{res.writeHead(up.statusCode,up.headers);up.pipe(res);res.on('close',()=>up.destroy());});req.pipe(proxy);proxy.on('error',()=>res.end());return;}const file=path.join(root,'client/dist',req.url==='/'?'index.html':req.url.split('?')[0]);fs.readFile(file,(err,data)=>{if(err){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(data);});});await new Promise(r=>web.listen(5173,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
 const ctx1=await browser.newContext({viewport:{width:1280,height:880},permissions:['microphone'],acceptDownloads:true}),ctx2=await browser.newContext({viewport:{width:390,height:844}});for(const ctx of [ctx1,ctx2])await ctx.addInitScript(()=>Object.defineProperty(crypto,'randomUUID',{value:undefined}));
 const a=await ctx1.newPage(),b=await ctx2.newPage();const errors=[];for(const p of [a,b])p.on('pageerror',e=>errors.push(e.message));
 async function register(p,username,name){await p.goto('http://localhost:5173');await p.getByRole('button',{name:'Создать аккаунт',exact:true}).click();await p.locator('[name=name]').fill(name);await p.locator('[name=username]').fill(username);await p.locator('[name=password]').fill('my-test-password');await p.getByRole('button',{name:'Создать аккаунт →'}).click();await p.getByLabel('Поиск пользователей и чатов').waitFor();}
 async function send(p,text){await p.getByLabel('Сообщение',{exact:true}).fill(text);await p.getByLabel('Отправить сообщение',{exact:true}).click();await p.locator('.messages .message-text').getByText(text,{exact:true}).waitFor();}
 const message=(p,text)=>p.locator('article.message').filter({has:p.locator('.message-text').getByText(text,{exact:true})});
 async function menu(p,text,action){const m=message(p,text);await m.locator('summary').click();await m.getByRole('button',{name:action,exact:true}).click();}
 await register(a,'anna','Анна Смирнова');await register(b,'max','Максим');await a.getByLabel('Поиск пользователей и чатов').fill('max');await a.locator('.chat-row').filter({hasText:'@max'}).click();await send(a,'Привет! Проверяем новую Волну.');await b.getByRole('button',{name:/Анна Смирнова/}).click();await message(b,'Привет! Проверяем новую Волну.').waitFor();
 await menu(a,'Привет! Проверяем новую Волну.','Редактировать');await a.getByLabel('Сообщение',{exact:true}).fill('Привет! Теперь здесь есть файлы и реакции.');await a.getByLabel('Сохранить изменения').click();await message(b,'Привет! Теперь здесь есть файлы и реакции.').waitFor();
 await menu(b,'Привет! Теперь здесь есть файлы и реакции.','Ответить');await send(b,'Класс! Проверяю с телефона.');assert.equal(await message(a,'Класс! Проверяю с телефона.').locator('.reply-quote').count(),1);
 await message(b,'Привет! Теперь здесь есть файлы и реакции.').locator('summary').click();await message(b,'Привет! Теперь здесь есть файлы и реакции.').getByLabel('Реакция ❤️').click();await message(a,'Привет! Теперь здесь есть файлы и реакции.').locator('.reactions').waitFor();
 await menu(a,'Привет! Теперь здесь есть файлы и реакции.','Закрепить');await b.locator('.pin-banner').waitFor();
 await menu(b,'Привет! Теперь здесь есть файлы и реакции.','В избранное');await b.getByLabel('Назад к чатам').click();await b.locator('.saved-button').click();await message(b,'Привет! Теперь здесь есть файлы и реакции.').waitFor();await menu(b,'Привет! Теперь здесь есть файлы и реакции.','Переслать');await b.getByRole('dialog',{name:'Переслать сообщение'}).getByRole('button',{name:'А Анна Смирнова'}).click();await b.getByLabel('Назад к чатам').click();await b.locator('.chat-row').filter({hasText:'Анна Смирнова'}).click();await b.locator('.forward-label').waitFor();
 await a.getByLabel('Выбрать файл',{exact:true}).setInputFiles({name:'План.txt',mimeType:'text/plain',buffer:Buffer.from('Файлы работают!')});await a.locator('.draft-context').getByText('План.txt',{exact:true}).waitFor();await a.getByLabel('Отправить сообщение',{exact:true}).click();const file=b.locator('.file-label').filter({hasText:'План.txt'});await file.getByRole('button',{name:'Загрузить'}).click();await file.getByRole('link',{name:'Скачать'}).waitFor();
 const imageBytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jI1sAAAAASUVORK5CYII=','base64');
 await a.getByLabel('Выбрать файл',{exact:true}).setInputFiles({name:'Фото.png',mimeType:'image/png',buffer:imageBytes});await a.locator('.draft-context').getByText('Фото.png',{exact:true}).waitFor();await a.getByLabel('Отправить сообщение',{exact:true}).click();await b.getByLabel('Открыть изображение Фото.png').click();await b.getByRole('dialog',{name:'Просмотр изображения'}).waitFor();await b.getByLabel('Закрыть изображение').click();
 await a.getByLabel('Поиск в переписке').click();await a.getByLabel('Текст поиска').fill('ПЛАН');await a.locator('.result-list').getByText('План.txt',{exact:true}).waitFor();await a.getByLabel('Закрыть панель').click();
 await a.locator('.mic-button').click();await a.waitForFunction(()=>document.querySelector('.mic-button')?.getAttribute('aria-pressed')==='true');await a.waitForTimeout(1200);await a.locator('.mic-button').click();await b.locator('.messages .voice-player[data-voice="true"]').waitFor();
 await send(a,'Это сообщение удалим');await menu(a,'Это сообщение удалим','Удалить у всех');await a.getByRole('dialog',{name:'Удалить сообщение',exact:true}).getByRole('button',{name:'Удалить',exact:true}).click();await b.locator('.messages').getByText('Сообщение удалено',{exact:true}).waitFor();
 await a.waitForTimeout(350);await a.screenshot({path:path.join(root,'artifacts','ui-desktop.png')});await b.screenshot({path:path.join(root,'artifacts','ui-mobile.png')});await b.reload();await b.locator('.chat-row').filter({hasText:'Анна Смирнова'}).click();await b.locator('.messages').getByText('Сообщение удалено',{exact:true}).waitFor();
 if(errors.length)throw Error(errors.join('\n'));console.log('PASS: rich messaging in two browsers; replies, edit, react, pin, saved, forward, file, search, tap-to-record and tap-to-send, delete, reload; randomUUID absent; no JS errors');
 await browser.close();await api.close();web.close();fs.rmSync(uploadDir,{recursive:true,force:true});process.exit(0);
})().catch(e=>{console.error(e);process.exit(1)});
