import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createApp,fixtureFetch as fetch} from './phone-fixture.mjs';

test('group/channel permissions, roles, invitations, bans, ownership and realtime revocation',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'volna-groups-'));const app=createApp({database:join(dir,'db')});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const port=app.server.address().port,base=`http://127.0.0.1:${port}/api`;
 const call=async(path,token,data)=>{const response=await fetch(base+path,{method:data===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(data===undefined?{}:{body:JSON.stringify(data)})});return {status:response.status,data:await response.json()};};
 const msg=(id,token,text='hello')=>call(`/chats/${id}/messages`,token,{text,client_id:randomUUID()});
 const sendSlow=(path,token,data)=>{const bytes=JSON.stringify(data);let req;const result=new Promise((resolve,reject)=>{req=http.request(base+path,{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','Content-Length':Buffer.byteLength(bytes)}},res=>{let raw='';res.on('data',x=>raw+=x);res.on('end',()=>resolve({status:res.statusCode,data:JSON.parse(raw)}));});req.on('error',reject);req.write(bytes.slice(0,1));});return {finish:()=>req.end(bytes.slice(1)),result};};
 try{
  const users=[];for(const username of ['owner','admin','member','outsider'])users.push((await call('/register','',{username,password:'test-password'})).data);
  const [a,b,c,d]=users;
  const create={kind:'group',title:'Тестовая группа',description:'История доступна участникам',client_id:randomUUID()};const group=(await call('/communities',a.token,create)).data.id;
  assert.equal((await call('/communities',a.token,create)).data.id,group);
  assert.equal((await call('/chats',a.token)).data.filter(x=>x.id===group).length,1);
  assert.equal((await call(`/communities/${group}`,d.token)).status,404);
  const originalInvite=(await call(`/communities/${group}/invite`,a.token,{})).data.token;
  assert.equal((await call('/invites/join',b.token,{token:originalInvite})).data.id,group);
  assert.equal((await call('/invites/join',b.token,{token:originalInvite})).status,200);
  await call(`/communities/${group}/add`,a.token,{user_id:c.user.id});
  assert.equal((await call(`/communities/${group}/role`,c.token,{user_id:c.user.id,role:'admin'})).status,403);
  await call(`/communities/${group}/role`,a.token,{user_id:b.user.id,role:'admin'});
  const message=(await msg(group,c.token,'Групповое сообщение')).data;
  assert.equal(message.sender_name,'member');
  assert.equal((await call(`/messages/${message.id}/pin`,c.token,{pinned:true})).status,403);
  assert.equal((await call(`/messages/${message.id}/pin`,b.token,{pinned:true})).status,200);
  assert.equal((await call(`/messages/${message.id}/edit`,b.token,{text:'bad'})).status,403);
  assert.equal((await call(`/messages/${message.id}/delete`,b.token,{})).status,200);
  assert.equal((await call(`/messages/${message.id}/delete`,b.token,{})).data.id,message.id);
  assert.equal((await call(`/communities/${group}/remove`,b.token,{user_id:a.user.id})).status,403);
  assert.equal((await call(`/communities/${group}/role`,b.token,{user_id:c.user.id,role:'admin'})).status,403);
  const streamController=new AbortController();const stream=await fetch(base+'/events',{headers:{Authorization:'Bearer '+c.token},signal:streamController.signal});const reader=stream.body.getReader();await reader.read();
  const slow=sendSlow(`/chats/${group}/messages`,c.token,{text:'after removal',client_id:randomUUID()});
  assert.equal((await call(`/communities/${group}/remove`,b.token,{user_id:c.user.id})).status,200);slow.finish();assert.equal((await slow.result).status,404);
  const event=await reader.read();assert.match(new TextDecoder().decode(event.value),/"type":"removed"/);streamController.abort();
  assert.equal((await call(`/chats/${group}/messages`,c.token)).status,404);
  assert.equal((await call('/invites/join',c.token,{token:originalInvite})).status,403);
  await call(`/communities/${group}/unban`,a.token,{user_id:c.user.id});assert.equal((await call('/invites/join',c.token,{token:originalInvite})).status,200);
  const newInvite=(await call(`/communities/${group}/invite`,a.token,{})).data.token;
  assert.equal((await call('/invites/join',d.token,{token:originalInvite})).status,404);
  app.db.prepare('UPDATE community_invites SET expires=? WHERE chat_id=?').run(Date.now()-1000,group);
  assert.equal((await call('/invites/join',d.token,{token:newInvite})).status,404);
  const limited=(await call(`/communities/${group}/invite`,a.token,{})).data.token;
  app.db.prepare('UPDATE community_invites SET uses=max_uses WHERE chat_id=?').run(group);
  assert.equal((await call('/invites/join',d.token,{token:limited})).status,410);
  await call(`/communities/${group}/revoke-invite`,a.token,{});assert.equal((await call('/invites/join',d.token,{token:limited})).status,404);
  assert.equal((await call(`/communities/${group}/leave`,a.token,{})).status,409);
  assert.equal((await call(`/communities/${group}/transfer`,a.token,{user_id:c.user.id})).status,200);
  const detail=(await call(`/communities/${group}`,c.token)).data;assert.equal(detail.role,'owner');assert.equal(detail.members.filter(m=>m.role==='owner').length,1);
  assert.equal((await call(`/communities/${group}/leave`,a.token,{})).status,200);
  assert.equal((await call('/chats',a.token)).data.some(x=>x.id===group),false);
  const channel=(await call('/communities',a.token,{kind:'channel',title:'Новости',client_id:randomUUID()})).data.id;
  await call(`/communities/${channel}/add`,a.token,{user_id:b.user.id});await call(`/communities/${channel}/add`,a.token,{user_id:c.user.id});
  assert.equal((await msg(channel,b.token)).status,403);
  assert.equal((await call(`/communities/${channel}`,b.token)).data.members.length,0);
  assert.equal((await call('/chats',b.token)).data.find(x=>x.id===channel).can_send,0);
  const post=(await msg(channel,a.token,'Публикация')).data;
  assert.equal((await call(`/messages/${post.id}/react`,b.token,{emoji:'👍',active:true})).status,200);
  assert.equal((await call(`/messages/${post.id}/pin`,b.token,{pinned:true})).status,403);
  assert.equal((await call(`/messages/${post.id}/forward`,b.token,{chat_id:channel,client_id:randomUUID()})).status,403);
  await call(`/communities/${channel}/role`,a.token,{user_id:b.user.id,role:'admin'});
  const ownPost=(await msg(channel,b.token,'От администратора')).data;
  assert.equal((await call(`/communities/${channel}`,b.token)).data.members.length,3);
  const slowEdit=sendSlow(`/messages/${ownPost.id}/edit`,b.token,{text:'after demotion'});
  await call(`/communities/${channel}/role`,a.token,{user_id:b.user.id,role:'member'});slowEdit.finish();assert.equal((await slowEdit.result).status,403);
  assert.equal((await msg(channel,b.token)).status,403);
  assert.equal((await call('/chats',c.token)).data.filter(x=>x.id===channel).length,1);
  // The server never persists a raw invitation secret.
  const secret=(await call(`/communities/${channel}/invite`,a.token,{})).data.token;
  assert.notEqual(app.db.prepare('SELECT token_hash FROM community_invites WHERE chat_id=?').get(channel).token_hash,secret);
  assert.equal(app.db.prepare('PRAGMA user_version').get().user_version,7);
 }finally{await app.close();rmSync(dir,{recursive:true,force:true});}
});
