import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {EventEmitter} from 'node:events';import {CallTones,callTone} from '../client/src/call-tones.mjs';
const require=createRequire(import.meta.url),{createUpdates}=require('../client/electron/updates.cjs'),{trustedRenderer,externalURL,validateConfig,rendererFile}=require('../client/electron/desktop-core.cjs');
test('desktop IPC origins, renderer paths, HTTPS feed and Telegram returns are confined',()=>{
 assert.equal(trustedRenderer('app://volna/index.html'),true);for(const s of ['https://volna.lknet.ru','app://other/index.html','app://volna.evil','app://u:p@volna','file:///a','javascript:alert(1)'])assert.equal(trustedRenderer(s),false);
 assert.equal(rendererFile('/app/dist','app://volna/assets/a.js'),'/app/dist/assets/a.js');for(const s of ['app://volna/%2f..%2fsecret','app://volna/assets/..%2f..%2fsecret','app://volna/%ff','https://volna/secret'])assert.equal(rendererFile('/app/dist',s),null);
 assert.equal(externalURL('https://example.com/doc'),'https://example.com/doc');for(const s of ['javascript:alert(1)','file:///a','https://u:p@example.com','volna://auth'])assert.equal(externalURL(s),null);
 assert.deepEqual(validateConfig({apiBase:'https://volna.lknet.ru/'}),{apiBase:'https://volna.lknet.ru',updateBase:'https://volna.lknet.ru/download/windows/'});for(const s of ['http://example.com','https://u:p@example.com','https://example.com/?url=evil','https://example.com/#evil'])assert.throws(()=>validateConfig({apiBase:s}));
});
class Updater extends EventEmitter{checks=0;downloads=0;async checkForUpdates(){this.checks++;this.emit('checking-for-update');this.emit('update-available',{version:'0.11.36'});}async downloadUpdate(){this.downloads++;this.emit('download-progress',{percent:42});this.emit('update-downloaded',{version:'0.11.36'});}}
function setup(supported=true){const updater=new Updater(),states=[];let installs=0,call=false;const controller=createUpdates({updater,version:'0.11.35',supported,publish:s=>states.push(s),install:()=>installs++,inCall:()=>call});return {updater,controller,states,installed:()=>installs,setCall:v=>call=v};}
test('Windows downloading and installation require Update; no automatic quit installation',async()=>{const {updater,controller,installed,states}=setup();assert.equal(updater.autoDownload,false);assert.equal(updater.autoInstallOnAppQuit,false);assert.equal(updater.allowDowngrade,false);await controller.check();assert.equal(controller.snapshot().status,'available');assert.equal(updater.downloads,0);assert.equal(installed(),0);await controller.update();assert.equal(updater.downloads,1);assert.equal(installed(),1);assert.ok(states.some(s=>s.percent===42));await controller.update();assert.equal(installed(),1);});
test('Windows ready update waits for call completion and explicit restart',async()=>{const {controller,installed,setCall}=setup();await controller.check();setCall(true);await controller.update();assert.equal(installed(),0);assert.equal(controller.snapshot().status,'ready');assert.equal(controller.install(),false);setCall(false);assert.equal(installed(),0);await controller.update();assert.equal(installed(),1);});
test('update errors, stale events and unsupported runtime never install',async()=>{const {updater,controller,installed}=setup();await controller.check();updater.downloadUpdate=async()=>{updater.emit('error',Error('checksum'));throw Error('checksum');};await controller.update();assert.equal(controller.snapshot().status,'error');assert.equal(installed(),0);updater.emit('download-progress',{percent:100});updater.emit('update-downloaded',{version:'0.11.36'});assert.equal(controller.snapshot().status,'error');assert.equal(controller.install(),false);await controller.check(true);assert.equal(controller.snapshot().manual,true);const blocked=setup(false);await blocked.controller.check();await blocked.controller.update();assert.equal(blocked.updater.checks,0);assert.equal(blocked.updater.downloads,0);});
test('ringback stops after answer/end and clears timers and audio nodes',()=>{assert.equal(callTone({incoming:false,status:'ringing'}),'ringback');assert.equal(callTone({incoming:true,status:'ringing'}),'incoming');for(const status of ['preparing','connecting','active'])assert.equal(callTone({incoming:false,status}),'');assert.equal(callTone(null),'');assert.equal(callTone({incoming:false,status:'ringing'},true),'');const tasks=new Map();let next=0,starts=0,stops=0,closed=0;const context={state:'running',currentTime:0,destination:{},resume:async()=>{},close:async()=>{closed++;},createGain:()=>({gain:{setValueAtTime(){},linearRampToValueAtTime(){}},connect(){},disconnect(){}}),createOscillator:()=>({frequency:{value:0},connect(){},disconnect(){},start(){starts++;},stop(){stops++;}})};const tones=new CallTones({createContext:()=>context,timers:{setInterval(fn,delay){tasks.set(++next,{fn,delay});return next;},clearInterval:id=>tasks.delete(id)}});tones.unlock();tones.set('ringback');assert.equal(starts,1);assert.equal([...tasks.values()][0].delay,4000);tones.set('ringback');assert.equal(starts,1);[...tasks.values()][0].fn();assert.equal(starts,2);tones.set('');assert.equal(tasks.size,0);assert.ok(stops>=2);tones.set('incoming');assert.equal([...tasks.values()][0].delay,1800);tones.close();assert.equal(closed,1);assert.equal(tasks.size,0);});
