import test from 'node:test';import assert from 'node:assert/strict';import {createApp} from '../server/index.mjs';import {randomUUID} from 'node:crypto';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {DatabaseSync} from 'node:sqlite';import {topicNotification} from '../server/topics.mjs';
async function fixture(t,options={}){const sent=[];let now=Date.now();const app=createApp({database:':memory:',...options,phoneAuthOptions:{smsReady:true,sender:async row=>{sent.push(row);return {id:'test'};},clock:()=>now}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.close());const base=`http://127.0.0.1:${app.server.address().port}/api`;
 async function call(path,token,data,method){const r=await fetch(base+path,{method:method||(data===undefined?'GET':'POST'),headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},...(data===undefined?{}:{body:JSON.stringify(data)})});return {status:r.status,data:await r.json()};}
 async function login(phone){now+=60001;const request=await call('/auth/sms/request','',{phone});assert.equal(request.status,200);const result=await call('/auth/sms/verify','',{sms_session_id:request.data.sms_session_id,code:sent.at(-1).code});assert.equal(result.status,200);return result.data;}
 return {app,call,login};}
test('public usernames: phone defaults, case-insensitive unique change, suggestions, reserved names and unchanged identity',async t=>{
 const {app,call,login}=await fixture(t),a=await login('+7 (968) 141-12-41'),b=await login('+79681411242');assert.equal(a.user.username,'79681411241');assert.equal(a.user.display_username,'@79681411241');assert.equal(a.user.profile_url,'https://volna.lknet.ru/79681411241');
 const changed=await call('/users/me/username',a.token,{username:'@NiCk'},'PATCH');assert.equal(changed.status,200);assert.equal(changed.data.user.id,a.user.id);assert.equal(changed.data.user.phone,a.user.phone);assert.equal(changed.data.username,'nick');
 assert.equal((await call('/public/users/79681411241')).status,404);const publicProfile=await call('/public/users/NICK');assert.equal(publicProfile.status,200);assert.equal(publicProfile.data.username,'nick');for(const key of ['phone','hash','token','refresh_token'])assert.equal(publicProfile.data[key],undefined);
 const check=await call('/users/username/check?username=Nick',b.token);assert.equal(check.data.available,false);assert.ok(check.data.suggestions.length>=3);for(const nick of check.data.suggestions)assert.equal((await call('/users/username/check?username='+nick,b.token)).data.available,true);
 assert.equal((await call('/users/me/username',b.token,{username:'NICK'},'PATCH')).status,409);for(const nick of ['api','admin','ab','bad nickname','кириллица','12345678'])assert.equal((await call('/users/me/username',b.token,{username:nick},'PATCH')).status,400);
 assert.throws(()=>app.db.prepare('UPDATE users SET username=? WHERE id=?').run('NICK',b.user.id),/UNIQUE/);
 const races=await Promise.all([call('/users/me/username',a.token,{username:'shared'},'PATCH'),call('/users/me/username',b.token,{username:'SHARED'},'PATCH')]);assert.deepEqual(races.map(x=>x.status).sort(),[200,409]);
});
test('user search: exact formatted phones, prefix usernames, exact-first order, old username disappears and collision-safe registration',async t=>{
 const {app,call,login}=await fixture(t),a=await login('+79001112233'),b=await login('+79001112234'),c=await login('+79001112235');
 await call('/users/me/username',b.token,{username:'alex'},'PATCH');await call('/users/me/username',c.token,{username:'alexander'},'PATCH');
 for(const q of ['+7 (900) 111-22-34','79001112234']){const result=await call('/users/search?q='+encodeURIComponent(q),a.token);assert.equal(result.data.users.length,1);assert.equal(result.data.users[0].id,b.user.id);assert.equal(result.data.users[0].phone,undefined);}
 const prefix=await call('/users/search?q=alex',a.token);assert.deepEqual(prefix.data.users.map(u=>u.username),['alex','alexander']);assert.equal((await call('/users/search?q=@alex',a.token)).data.users[0].id,b.user.id);assert.equal((await call('/users/search?q=+7900111',a.token)).data.users.length,0);assert.equal((await call('/users/search?q=7900',a.token)).data.users.length,0);
 app.db.prepare('UPDATE users SET username=? WHERE id=?').run('79001119999',c.user.id);const d=await login('+79001119999');assert.equal(d.user.username,'79001119999_1');assert.equal((await login('+79001112234')).user.id,b.user.id);assert.equal((await login('+79001112234')).user.username,'alex');
});
test('group topics: isolated histories and receipts, closed sending, permission policy, creator management and parent membership cascade',async t=>{
 const {call,login}=await fixture(t),a=await login('+79001230001'),b=await login('+79001230002'),c=await login('+79001230003');
 const group=(await call('/communities',a.token,{kind:'group',title:'Автоклуб',description:'',client_id:randomUUID()})).data.id;await call(`/communities/${group}/add`,a.token,{user_id:b.user.id});
 assert.equal((await call(`/groups/${group}/topics`,b.token,{name:'Ремонт'})).status,403);await call(`/groups/${group}/topics/settings`,a.token,{create_policy:'all'});
 const created=await call(`/groups/${group}/topics`,b.token,{name:'Ремонт',description:'Обсуждаем машины',icon:'🔧',client_id:randomUUID()});assert.equal(created.status,201);const topic=created.data.id;
 const first=await call(`/groups/${group}/topics/${topic}/messages`,a.token,{text:'Только в ремонте',client_id:randomUUID()});assert.equal(first.status,201);assert.equal(first.data.topic_id,topic);assert.equal(first.data.group_id,group);
 const general=await call(`/chats/${group}/messages`,a.token,{text:'Общий чат',client_id:randomUUID()});assert.equal(general.status,201);assert.equal((await call(`/chats/${group}/messages`,b.token)).data.length,1);assert.equal((await call(`/groups/${group}/topics/${topic}/messages`,b.token)).data[0].id,first.data.id);
 assert.equal((await call(`/groups/${group}/topics`,b.token)).data.topics[0].unread_count,1);await call(`/chats/${group}/read`,b.token,{message_id:general.data.id});assert.equal((await call(`/groups/${group}/topics`,b.token)).data.topics[0].unread_count,1);await call(`/chats/${topic}/read`,b.token,{message_id:first.data.id});assert.equal((await call(`/groups/${group}/topics`,b.token)).data.topics[0].unread_count,0);
 assert.equal((await call(`/groups/${group}/topics/${topic}`,b.token,{closed:true},'PATCH')).status,200);assert.equal((await call(`/chats/${topic}/messages`,a.token,{text:'Нельзя',client_id:randomUUID()})).status,403);assert.equal((await call(`/chats/${topic}/messages`,a.token)).status,200);await call(`/groups/${group}/topics/${topic}`,a.token,{closed:false},'PATCH');
 assert.equal((await call(`/groups/${group}/topics/${topic}/messages`,c.token)).status,404);await call(`/communities/${group}/add`,a.token,{user_id:c.user.id});assert.equal((await call(`/chats/${topic}/messages`,c.token)).status,200);assert.equal((await call(`/groups/${group}/topics/${topic}`,c.token,{name:'Хак'},'PATCH')).status,403);
 await call(`/communities/${group}/role`,a.token,{user_id:c.user.id,role:'admin'});assert.equal((await call(`/groups/${group}/topics/${topic}`,c.token,{description:'Обновлено'},'PATCH')).status,200);await call(`/communities/${group}/role`,a.token,{user_id:c.user.id,role:'member'});await call(`/communities/${group}/remove`,a.token,{user_id:c.user.id});assert.equal((await call(`/chats/${topic}/messages`,c.token)).status,404);
 assert.equal((await call(`/communities/${topic}/invite`,a.token,{})).status,400);assert.equal((await call(`/groups/${group}/topics/${topic}`,b.token,undefined,'DELETE')).status,200);assert.equal((await call(`/chats/${topic}/messages`,a.token)).status,404);assert.equal((await call(`/groups/${group}/topics`,a.token)).data.topics.length,0);
});
test('topic notification preferences are private and durable; mentions match whole usernames',async t=>{
 const {app,call,login}=await fixture(t),a=await login('+79001234001'),b=await login('+79001234002');await call('/users/me/username',b.token,{username:'alex'},'PATCH');const g=(await call('/communities',a.token,{kind:'group',title:'Группа',client_id:randomUUID()})).data.id;await call(`/communities/${g}/add`,a.token,{user_id:b.user.id});const topic=(await call(`/groups/${g}/topics`,a.token,{name:'Новости'})).data.id;
 await call(`/groups/${g}/topics/${topic}/notifications`,b.token,{mode:'mentions'});assert.equal(topicNotification(app.db,topic,b.user.id,'Привет'),false);assert.equal(topicNotification(app.db,topic,b.user.id,'Привет @Alex!'),true);assert.equal(topicNotification(app.db,topic,b.user.id,'@alexander'),false);assert.equal((await call(`/groups/${g}/topics`,a.token)).data.topics[0].notification_mode,'all');
 await call(`/groups/${g}/topics/${topic}/notifications`,b.token,{mode:'none'});assert.equal(topicNotification(app.db,topic,b.user.id,'@alex'),false);assert.equal((await call(`/groups/${g}/topics/${topic}/notifications`,b.token,{mode:'wrong'})).status,400);
});
test('0.12 phone database upgrades aliases once, preserves IDs/sessions/topics and notification preferences after restart',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'volna-public-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const database=join(dir,'db');const legacy=new DatabaseSync(database);
 legacy.exec("CREATE TABLE users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,name TEXT NOT NULL,phone TEXT UNIQUE NOT NULL);INSERT INTO users VALUES(1500000001,'u1234567890abcdef','Алексей','+79000000001');");legacy.close();
 let app=createApp({database}),base='';async function start(){await new Promise(r=>app.server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${app.server.address().port}/api`;}await start();t.after(()=>app.close());
 assert.equal(app.db.prepare('SELECT username FROM users').get().username,'79000000001');assert.equal(app.db.prepare('SELECT id FROM users').get().id,1500000001);
 // A subsequently chosen alias that happens to resemble the old format must never be replaced again.
 app.db.prepare('UPDATE users SET username=? WHERE id=?').run('uabcdef1234567890',1500000001);await app.close();app=createApp({database});await start();assert.equal(app.db.prepare('SELECT username FROM users').get().username,'uabcdef1234567890');
 const {createHash}=await import('node:crypto');const token='test-session',hash=createHash('sha256').update(token).digest('hex');app.db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash,1500000001,Date.now()+3600000);
 async function call(path,data,method){const r=await fetch(base+path,{method:method||(data===undefined?'GET':'POST'),headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},...(data===undefined?{}:{body:JSON.stringify(data)})});assert.ok(r.ok,await r.clone().text());return r.json();}
 const group=(await call('/communities',{kind:'group',title:'Группа',client_id:randomUUID()})).id;const topic=(await call(`/groups/${group}/topics`,{name:'Сохранится'})).id;await call(`/chats/${topic}/messages`,{text:'История',client_id:randomUUID()});await call(`/groups/${group}/topics/${topic}/notifications`,{mode:'mentions'});
 await app.close();app=createApp({database});await start();assert.equal((await call('/me')).id,1500000001);const details=await call(`/groups/${group}/topics`);assert.equal(details.topics[0].notification_mode,'mentions');assert.equal((await call(`/chats/${topic}/messages`))[0].text,'История');
});
test('topic SSE delivers data to all members but suppresses notification per recipient',async t=>{
 const {app,call,login}=await fixture(t),a=await login('+79009991001'),b=await login('+79009991002');const group=(await call('/communities',a.token,{kind:'group',title:'Уведомления',client_id:randomUUID()})).data.id;await call(`/communities/${group}/add`,a.token,{user_id:b.user.id});const topic=(await call(`/groups/${group}/topics`,a.token,{name:'Подтема'})).data.id;await call(`/groups/${group}/topics/${topic}/notifications`,b.token,{mode:'none'});
 const controller=new AbortController();t.after(()=>controller.abort());const stream=await fetch(`http://127.0.0.1:${app.server.address().port}/api/events`,{headers:{Authorization:'Bearer '+b.token},signal:controller.signal});const reader=stream.body.getReader();await reader.read();
 await call(`/chats/${topic}/messages`,a.token,{text:'Данные остаются доступны',client_id:randomUUID()});const chunk=await reader.read();const frames=new TextDecoder().decode(chunk.value).split('\n\n').filter(x=>x.startsWith('data: ')).map(x=>JSON.parse(x.slice(6)));const event=frames.find(x=>x.type==='message');assert.equal(event.notify,false);assert.equal(event.message.topic_id,topic);assert.equal(event.message.text,'Данные остаются доступны');controller.abort();
});
test('public avatars expose only the selected image and stop working on hide or nickname change',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'volna-avatar-public-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const f=await fixture(t,{uploads:dir}),a=await f.login('+79001234501');const base=`http://127.0.0.1:${f.app.server.address().port}/api`;
 const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aHe8AAAAASUVORK5CYII=','base64');
 const upload=await fetch(base+'/uploads',{method:'POST',headers:{Authorization:'Bearer '+a.token,'Content-Type':'image/png','X-File-Name':'avatar.png'},body:png});assert.equal(upload.status,201);const file=await upload.json();
 assert.equal((await f.call('/profile',a.token,{name:'Фото',bio:'',avatar_id:file.id})).status,200);const publicProfile=await f.call('/public/users/'+a.user.username);assert.equal(publicProfile.data.phone,undefined);const image=await fetch(base+'/public/users/'+a.user.username+'/avatar');assert.equal(image.status,200);assert.equal(image.headers.get('content-type'),'image/png');assert.deepEqual(Buffer.from(await image.arrayBuffer()),png);
 assert.equal((await fetch(base+'/files/'+file.id)).status,401);await f.call('/users/me/username',a.token,{username:'picture'},'PATCH');assert.equal((await fetch(base+'/public/users/'+a.user.username+'/avatar')).status,404);assert.equal((await fetch(base+'/public/users/picture/avatar')).status,200);
 await f.call('/profile',a.token,{name:'Фото',bio:'',avatar_id:file.id,avatar_hidden:true});assert.equal((await fetch(base+'/public/users/picture/avatar')).status,404);assert.equal((await f.call('/public/users/picture')).data.avatar_url,null);
});
