import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,copyFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';
const source=process.cwd();
function file(p,s,mode=0o644){mkdirSync(resolve(p,'..'),{recursive:true});writeFileSync(p,s,{mode});}
test('Windows publication checks feed/hash before update and preserves .env and previous download',()=>{const dir=mkdtempSync(join(tmpdir(),'volna-windows-'));try{
 file(join(dir,'.env'),'PRESERVE=yes\n');file(join(dir,'compose.yaml'),'services: {}\n');for(const p of ['package.json','client/package.json','scripts/build-windows.sh','scripts/check-windows-space.py','scripts/publish-windows.py','compose.build-host.yaml']){mkdirSync(resolve(dir,p,'..'),{recursive:true});copyFileSync(join(source,p),join(dir,p));}
 const log=join(dir,'calls');file(join(dir,'bin/docker'),'#!/bin/sh\necho "$*" >> "$TEST_LOG"\n',0o755);file(join(dir,'scripts/update.sh'),'#!/bin/sh\necho UPDATE >> "$TEST_LOG"\nprintf "NETWORK=%s\\n" "${VOLNA_BUILD_NETWORK:-default}" >> "$TEST_LOG"\n',0o755);file(join(dir,'scripts/check-downloads.sh'),'#!/bin/sh\necho CHECK >> "$TEST_LOG"\n',0o755);
 const v=JSON.parse(readFileSync(join(source,'package.json'))).version,name=`Volna-Setup-${v}.exe`,data=Buffer.alloc(1_000_000);data.write('MZ');data.writeUInt32LE(128,60);data.write('PE\0\0',128);const release=join(dir,'artifacts/windows-release',v),sha512=createHash('sha512').update(data).digest('base64');file(join(release,name),data);file(join(release,name+'.blockmap'),'blockmap');file(join(release,'release-info.json'),JSON.stringify({version:v,installer:name,size:data.length,sha512,sha256:createHash('sha256').update(data).digest('hex')}));const metadata=`version: ${v}\nfiles:\n  - url: ${name}\n    sha512: ${sha512}\n    size: ${data.length}\npath: ${name}\nsha512: ${sha512}\n`;file(join(release,'latest.yml'),metadata);
 const env={...process.env,PATH:join(dir,'bin')+':'+process.env.PATH,TEST_LOG:log};let r=spawnSync('sh',['scripts/build-windows.sh'],{cwd:dir,env,encoding:'utf8'});assert.equal(r.status,0,r.stderr);assert.deepEqual(readFileSync(join(dir,'client/public/download/volna-windows.exe')),data);assert.equal(readFileSync(join(dir,'.env'),'utf8'),'PRESERVE=yes\n');assert.equal(readFileSync(log,'utf8').split('\n').filter(s=>s==='UPDATE').length,1);
 file(join(release,'latest.yml'),metadata.replace('version: '+v,'version: 99.0.0'));r=spawnSync('sh',['scripts/build-windows.sh'],{cwd:dir,env,encoding:'utf8'});assert.notEqual(r.status,0);assert.match(r.stderr,/feed/);assert.equal(readFileSync(join(dir,'client/public/download/windows/latest.yml'),'utf8'),metadata);assert.equal(readFileSync(log,'utf8').split('\n').filter(s=>s==='UPDATE').length,1);
 file(join(release,'latest.yml'),metadata);data[500]=1;file(join(release,name),data);r=spawnSync('sh',['scripts/build-windows.sh'],{cwd:dir,env,encoding:'utf8'});assert.notEqual(r.status,0);assert.match(r.stderr,/checksum/);assert.equal(readFileSync(log,'utf8').split('\n').filter(s=>s==='UPDATE').length,1);
 data[500]=0;file(join(release,name),data);file(log,'');r=spawnSync('sh',['scripts/build-windows.sh'],{cwd:dir,env:{...env,VOLNA_BUILD_NETWORK:'host'},encoding:'utf8'});assert.equal(r.status,0,r.stderr);const hostLog=readFileSync(log,'utf8');assert.match(hostLog,/compose -f compose.yaml -f compose.build-host.yaml --profile build run --build --rm windows-builder/);assert.match(hostLog,/UPDATE\nNETWORK=host\nCHECK/);assert.equal(readFileSync(join(dir,'.env'),'utf8'),'PRESERVE=yes\n');
 }finally{rmSync(dir,{recursive:true,force:true});}});
test('combined builder stops on either failure and updates services only after both clients',()=>{const dir=mkdtempSync(join(tmpdir(),'volna-combined-'));try{mkdirSync(join(dir,'scripts'),{recursive:true});copyFileSync(join(source,'scripts/build-clients.sh'),join(dir,'scripts/build-clients.sh'));const log=join(dir,'calls');for(const client of ['android','windows'])file(join(dir,`scripts/build-${client}.sh`),`#!/bin/sh\ntest "$VOLNA_BUILD_PUBLISH_ONLY" = 1 || exit 90\necho ${client} >> "$TEST_LOG"\nif [ "$TEST_FAIL" = ${client} ]; then exit 9; fi\n`,0o755);for(const step of ['update','check-downloads'])file(join(dir,`scripts/${step}.sh`),`#!/bin/sh\necho ${step} >> "$TEST_LOG"\n`,0o755);function run(fail){file(log,'');return spawnSync('sh',['scripts/build-clients.sh'],{cwd:dir,env:{...process.env,TEST_LOG:log,TEST_FAIL:fail},encoding:'utf8'});}assert.equal(run('').status,0);assert.equal(readFileSync(log,'utf8'),'android\nwindows\nupdate\ncheck-downloads\n');assert.equal(run('android').status,9);assert.equal(readFileSync(log,'utf8'),'android\n');assert.equal(run('windows').status,9);assert.equal(readFileSync(log,'utf8'),'android\nwindows\n');}finally{rmSync(dir,{recursive:true,force:true});}});
