import {readFileSync,writeFileSync,unlinkSync} from 'node:fs';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomBytes} from 'node:crypto';
import {inspectEmojiPng} from './emoji-media.mjs';
import {UNICODE_EMOJI_VERSION} from '../shared/emoji-text.mjs';
const fail=(status,message)=>Object.assign(Error(message),{status});
export function emojiEngine({db,uploads,body,json,getItem,pack,usage,publish}){
 const packId='00000000000000000000000000000003';
 db.exec(`CREATE TABLE IF NOT EXISTS emoji_asset_metadata(item_id TEXT PRIMARY KEY REFERENCES expression_items(id),sha256 TEXT NOT NULL,width INTEGER NOT NULL,height INTEGER NOT NULL,format TEXT NOT NULL,size_bytes INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS emoji_reports(id INTEGER PRIMARY KEY,reporter_id INTEGER NOT NULL REFERENCES users(id),pack_id TEXT NOT NULL REFERENCES expression_packs(id),reason TEXT NOT NULL,created INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS emoji_seeded(user_id INTEGER PRIMARY KEY REFERENCES users(id));
 CREATE TABLE IF NOT EXISTS emoji_audit(id INTEGER PRIMARY KEY,actor_id INTEGER NOT NULL REFERENCES users(id),pack_id TEXT NOT NULL,action TEXT NOT NULL,created INTEGER NOT NULL);`);
 for(const [name,definition] of [['description',"TEXT NOT NULL DEFAULT ''"],['slug','TEXT'],['status',"TEXT NOT NULL DEFAULT 'published'"],['updated',"INTEGER NOT NULL DEFAULT 0"]])if(!db.prepare('PRAGMA table_info(expression_packs)').all().some(c=>c.name===name))db.exec(`ALTER TABLE expression_packs ADD COLUMN ${name} ${definition}`);
 const maximum=Math.floor(Math.max(1,Math.min(200,Number(process.env.EMOJI_PACK_MAX_ITEMS)||200)));
 function metadata(item){let row=db.prepare('SELECT * FROM emoji_asset_metadata WHERE item_id=?').get(item.id);if(!row&&item.mime==='image/png'){try{const m=inspectEmojiPng(readFileSync(join(uploads,item.attachment_id)));db.prepare('INSERT OR IGNORE INTO emoji_asset_metadata VALUES(?,?,?,?,?,?)').run(item.id,m.sha256,m.width,m.height,m.format,m.size_bytes);row={...m};}catch{}}return {...item,...row,favorite:!!item.favorite,keywords:Array.isArray(item.keywords)?item.keywords:String(item.keywords||'').split('|').filter(Boolean),emoji_id:item.id,fallback_unicode:item.fallback,title:item.label,media_url:item.url||'/api/files/'+item.attachment_id,preview_url:item.url||'/api/files/'+item.attachment_id,is_animated:item.mime.startsWith('video/')||item.mime==='image/gif',is_free:true};}
 function seed(uid){const root=fileURLToPath(new URL('./assets/emoji/',import.meta.url)),items=JSON.parse(readFileSync(join(root,'catalog.json'),'utf8'));
 if(!db.prepare('SELECT 1 FROM expression_packs WHERE id=?').get(packId)){const written=[];db.exec('BEGIN IMMEDIATE');try{db.prepare('INSERT INTO expression_packs(id,owner_id,title,kind,public,created,builtin,slug,description) VALUES(?,?,?,\'emoji\',1,?,1,?,?)').run(packId,uid,'Волна · 24 эмоции',Date.now(),'volna-emotions','Фирменный статичный набор Волны');for(let i=0;i<items.length;i++){const a=items[i],bytes=readFileSync(join(root,a.file)),file=randomBytes(24).toString('hex'),id='ee'+String(i+1).padStart(30,'0'),m=inspectEmojiPng(bytes,{exact:true});writeFileSync(join(uploads,file),bytes,{flag:'wx',mode:0o600});written.push(file);db.prepare('INSERT INTO attachments VALUES(?,?,?,?,?,?)').run(file,uid,a.file,'image/png',bytes.length,Date.now());db.prepare('INSERT INTO expression_items VALUES(?,?,?,?,?,?,?)').run(id,packId,file,a.title,a.keywords.join('|'),a.fallback,i);db.prepare('INSERT INTO emoji_asset_metadata VALUES(?,?,?,?,?,?)').run(id,m.sha256,m.width,m.height,m.format,m.size_bytes);}db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');for(const f of written){try{unlinkSync(join(uploads,f));}catch{}}throw e;}}
 if(!db.prepare('SELECT 1 FROM emoji_seeded WHERE user_id=?').get(uid)){db.prepare('INSERT OR IGNORE INTO expression_installs VALUES(?,?)').run(uid,packId);db.prepare('INSERT OR IGNORE INTO emoji_seeded VALUES(?)').run(uid);}
 }
 const dto=(p,uid)=>{const value=pack(p,uid);return {...value,pack_id:p.id,owner:db.prepare('SELECT id,name,username FROM users WHERE id=?').get(p.owner_id),items:value.items.map(metadata),url:'/app?emoji_pack='+p.id};};
 const allowed=(p,uid)=>p&&p.status!=='blocked'&&p.status!=='deleted'&&(p.public||p.owner_id===uid);
 const notice=p=>publish?.([...new Set([p.owner_id,...db.prepare('SELECT user_id FROM expression_installs WHERE pack_id=?').all(p.id).map(x=>x.user_id)])],{type:'emoji_pack.updated',pack_id:p.id,version:p.updated||Date.now()});
 const moderators=()=>new Set((process.env.EMOJI_MODERATOR_USER_IDS||'').split(',').map(Number).filter(n=>Number.isSafeInteger(n)&&n>0));
 async function handle(req,res,url,uid){const path=url.pathname,method=req.method;if(!/^\/api\/v1\/emoji(?:\/|$)/.test(path))return false;seed(uid);
 if(path==='/api/v1/emoji/config'&&method==='GET'){json(res,200,{stage:'MVP',unicode_version:UNICODE_EMOJI_VERSION,formats:['png'],input_formats:['png','webp'],animated_formats:[],canvas:100,max_bytes:262144,max_pack_items:maximum,moderator:moderators().has(uid)});return true;}
 if(path==='/api/v1/emoji/categories'&&method==='GET'){json(res,200,{unicode_version:UNICODE_EMOJI_VERSION,categories:['faces','people','animals','food','travel','activity','objects','symbols','flags']});return true;}
 if(path==='/api/v1/emoji/uploads'&&method==='POST'){const d=await body(req),f=db.prepare('SELECT * FROM attachments WHERE id=? AND owner_id=?').get(d.attachment_id||'',uid);if(!f||f.mime!=='image/png')throw fail(400,'Для Emoji MVP загрузите PNG 100×100');const m=inspectEmojiPng(readFileSync(join(uploads,f.id)),{exact:true});json(res,200,{id:f.id,status:'ready',...m});return true;}
 if(path==='/api/v1/emoji/packs'&&method==='GET'){const q=(url.searchParams.get('q')||'').trim().toLocaleLowerCase('ru'),section=url.searchParams.get('section')||'all',offset=Number(url.searchParams.get('offset')||0);if(!Number.isSafeInteger(offset)||offset<0||offset>10000||!['all','installed','own'].includes(section))throw fail(400,'Некорректная пагинация');const extra=section==='installed'?' AND EXISTS(SELECT 1 FROM expression_installs s WHERE s.pack_id=p.id AND s.user_id=?)':section==='own'?' AND p.owner_id=?':'';const rows=db.prepare(`SELECT p.* FROM expression_packs p WHERE p.kind='emoji' AND p.status='published' AND (p.public=1 OR p.owner_id=?) AND instr(casefold(p.title||' '||p.description),?)>0${extra} ORDER BY p.builtin DESC,p.created DESC,p.id LIMIT 21 OFFSET ?`).all(uid,q,...(extra?[uid]:[]),offset);json(res,200,{packs:rows.slice(0,20).map(p=>dto(p,uid)),more:rows.length>20,next_offset:offset+Math.min(rows.length,20)});return true;}
 if(['/api/v1/emoji','/api/v1/emoji/search'].includes(path)&&method==='GET'){const q=(url.searchParams.get('q')||'').trim().toLocaleLowerCase('ru'),offset=Number(url.searchParams.get('offset')||0),section=url.searchParams.get('section')||'catalog',pid=url.searchParams.get('pack_id')||'';if(!Number.isSafeInteger(offset)||offset<0||offset>10000||!['catalog','installed','recent','favorite'].includes(section))throw fail(400,'Некорректный фильтр');const filter=section==='installed'?' AND EXISTS(SELECT 1 FROM expression_installs s WHERE s.pack_id=p.id AND s.user_id=?)':section==='recent'?' AND u.used>0':section==='favorite'?' AND u.favorite=1':'';const rows=db.prepare(`SELECT i.*,p.kind,p.title AS pack_title,a.name,a.mime,a.size,COALESCE(u.favorite,0) favorite FROM expression_items i JOIN expression_packs p ON p.id=i.pack_id JOIN attachments a ON a.id=i.attachment_id LEFT JOIN expression_usage u ON u.item_id=i.id AND u.user_id=? WHERE p.kind='emoji' AND p.status='published' AND (p.public=1 OR p.owner_id=?) AND (?='' OR p.id=?) AND (instr(casefold(i.label||' '||i.keywords||' '||p.title),?)>0 OR i.fallback=?)${filter} ORDER BY CASE WHEN casefold(i.label)=? THEN 0 WHEN i.fallback=? THEN 1 ELSE 2 END,COALESCE(u.used,0) DESC,COALESCE(u.count,0) DESC,p.builtin DESC,i.position,i.id LIMIT 61 OFFSET ?`).all(uid,uid,pid,pid,q,q,...(section==='installed'?[uid]:[]),q,q,offset);json(res,200,{items:rows.slice(0,60).map(metadata),more:rows.length>60,next_offset:offset+Math.min(60,rows.length)});return true;}
 const match=path.match(/^\/api\/v1\/emoji\/packs\/([a-f0-9]{32})(?:\/(install|report|moderate))?$/);if(match){const p=db.prepare("SELECT * FROM expression_packs WHERE id=? AND kind='emoji'").get(match[1]);if(!p)throw fail(404,'Набор не найден');const action=match[2];
 if(action==='moderate'&&method==='POST'){if(!moderators().has(uid))throw fail(403,'Нужны права модератора');const d=await body(req);if(!['blocked','published'].includes(d.status))throw fail(400,'Некорректный статус');db.prepare('UPDATE expression_packs SET status=?,updated=? WHERE id=?').run(d.status,Date.now(),p.id);db.prepare('INSERT INTO emoji_audit(actor_id,pack_id,action,created) VALUES(?,?,?,?)').run(uid,p.id,d.status,Date.now());notice(p);publish?.(db.prepare('SELECT id FROM users').all().map(u=>u.id),{type:'emoji_asset.unavailable',pack_id:p.id});json(res,200,{ok:true});return true;}
 if(!allowed(p,uid))throw fail(404,'Набор недоступен');if(!action&&method==='GET'){json(res,200,dto(p,uid));return true;}
 if(action==='install'&&['POST','DELETE'].includes(method)){if(method==='POST')db.prepare('INSERT OR IGNORE INTO expression_installs VALUES(?,?)').run(uid,p.id);else db.prepare('DELETE FROM expression_installs WHERE user_id=? AND pack_id=?').run(uid,p.id);publish?.([uid],{type:'emoji_pack.updated',pack_id:p.id});json(res,200,{ok:true});return true;}
 if(action==='report'&&method==='POST'){const d=await body(req);if(typeof d.reason!=='string'||!d.reason.trim()||d.reason.length>500)throw fail(400,'Укажите причину жалобы до 500 символов');if(db.prepare('SELECT 1 FROM emoji_reports WHERE reporter_id=? AND pack_id=?').get(uid,p.id))throw fail(409,'Жалоба уже отправлена');db.prepare('INSERT INTO emoji_reports(reporter_id,pack_id,reason,created) VALUES(?,?,?,?)').run(uid,p.id,d.reason.trim(),Date.now());json(res,201,{ok:true});return true;}
 if(!action&&['PATCH','DELETE'].includes(method)){if(p.owner_id!==uid||p.builtin)throw fail(403,'Нельзя изменять этот набор');if(method==='DELETE')db.prepare("UPDATE expression_packs SET status='deleted',updated=? WHERE id=?").run(Date.now(),p.id);else{const d=await body(req);if(typeof d.title!=='string'||!d.title.trim()||d.title.length>64||typeof d.description!=='string'||d.description.length>500)throw fail(400,'Название до 64 и описание до 500 символов');db.prepare('UPDATE expression_packs SET title=?,description=?,updated=? WHERE id=?').run(d.title.trim(),d.description,Date.now(),p.id);}notice(p);json(res,200,{ok:true});return true;}
 }
 const item=path.match(/^\/api\/v1\/emoji\/([a-f0-9]{32})(?:\/(favorite|use))?$/);if(item){const row=getItem(item[1],uid);if(row.kind!=='emoji')throw fail(404,'Эмодзи не найден');if(!item[2]&&method==='GET'){json(res,200,metadata(row));return true;}if(method==='POST'&&item[2]){const d=await body(req);if(item[2]==='favorite'&&typeof d.active!=='boolean')throw fail(400,'Укажите active');usage(uid,row.id,item[2]==='use',item[2]==='favorite'?d.active:undefined);publish?.([uid],{type:'emoji_pack.updated',pack_id:row.pack_id});json(res,200,{ok:true});return true;}}
 if(path==='/api/v1/emoji/reports'&&method==='GET'){if(!moderators().has(uid))throw fail(403,'Нужны права модератора');json(res,200,db.prepare('SELECT r.*,p.title FROM emoji_reports r JOIN expression_packs p ON p.id=r.pack_id ORDER BY r.id DESC LIMIT 100').all());return true;}
 return false;}
 return {handle,seed,metadata,maximum};
}
