export const UNICODE_EMOJI_VERSION='15.1';
const segmenter=new Intl.Segmenter('und',{granularity:'grapheme'});
export function segments(text){return [...segmenter.segment(text)].map(s=>({start:s.index,end:s.index+s.segment.length,text:s.segment}));}
export function isEmoji(value){return typeof value==='string'&&value.length<=32&&segments(value).length===1&&/^(?:\p{Regional_Indicator}{2}|[0-9#*]\ufe0f?\u20e3|\p{Extended_Pictographic}[\p{Extended_Pictographic}\p{Emoji_Modifier}\u200d\ufe0f\u{e0020}-\u{e007f}]*)$/u.test(value);}
export function boundaries(text){return new Set([0,text.length,...segments(text).flatMap(s=>[s.start,s.end])]);}
export function snapSelection(text,start,end=start){const parts=segments(text),a=Math.max(0,Math.min(text.length,start)),b=Math.max(a,Math.min(text.length,end));return [parts.find(s=>s.start<a&&s.end>a)?.start??a,parts.find(s=>s.start<b&&s.end>b)?.end??b];}
export function replaceText(text,entities=[],start,end,replacement,inserted=[]){[start,end]=snapSelection(text,start,end);const delta=replacement.length-(end-start);return {text:text.slice(0,start)+replacement+text.slice(end),entities:[...entities.filter(e=>e.start+e.length<=start||e.start>=end).map(e=>({...e,start:e.start>=end?e.start+delta:e.start})),...inserted.map(e=>({...e,start:e.start+start}))].sort((a,b)=>a.start-b.start),caret:start+replacement.length};}
export function reconcileEntities(before,after,entities=[]){let a=0;while(a<before.length&&a<after.length&&before[a]===after[a])a++;let b=before.length,c=after.length;while(b>a&&c>a&&before[b-1]===after[c-1]){b--;c--;}const delta=after.length-before.length,edges=boundaries(after);return {text:after,entities:entities.filter(e=>e.start+e.length<=a||e.start>=b).flatMap(e=>{const start=e.start>=b?e.start+delta:e.start;return edges.has(start)&&edges.has(start+e.length)&&before.slice(e.start,e.start+e.length)===after.slice(start,start+e.length)?[{...e,start}]:[];}),caret:c};}
export function deleteGrapheme(text,entities,start,end,direction){[start,end]=snapSelection(text,start,end);if(start===end){const parts=segments(text);const s=direction==='backward'?parts.findLast(s=>s.end<=start):parts.find(s=>s.start>=end);if(!s)return null;start=s.start;end=s.end;}return replaceText(text,entities,start,end,'');}
