const app=document.querySelector('#app'),modal=document.querySelector('#modal');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Date(v).toLocaleString('ru-RU'):'—';
const bytes=v=>{const n=Number(v||0);return n>=1073741824?(n/1073741824).toFixed(1)+' ГБ':n>=1048576?(n/1048576).toFixed(1)+' МБ':n>=1024?(n/1024).toFixed(1)+' КБ':n+' Б';};
const nav={stats:'Обзор',users:'Пользователи',chats:'Чаты и участники',messages:'Сообщения',files:'Файлы',packs:'Эмодзи и стикеры',sms:'SMS и вход',devices:'Устройства',calls:'Звонки',settings:'Настройки',announcement:'Объявление',backups:'Резервные копии',audit:'Журнал действий','admin-sessions':'Сеансы администратора'};
let chatFilter='',session=null,view='stats',page=1,query='',data=null,challenge=null,config={},loadId=0;
async function api(path,payload){const r=await fetch('/admin/api/'+path,{method:payload===undefined?'GET':'POST',credentials:'same-origin',headers:payload===undefined?{}:{'Content-Type':'application/json','X-Admin-CSRF':session?.csrf_token||''},...(payload===undefined?{}:{body:JSON.stringify(payload)})});let value;try{value=await r.json();}catch{throw Error('Сервер не вернул ответ. Проверьте соединение.');}if(!r.ok){if(r.status===401&&session){session=null;modal.close();login();}throw Error(value.error||'Ошибка '+r.status);}return value;}
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.hidden=true,6500);}
function btn(label,action,id='',extra='',danger=false){return `<button type="button" class="small ${danger?'danger':''}" data-action="${action}" data-id="${esc(id)}" ${extra}>${esc(label)}</button>`;}
function badge(v,bad=false){return `<span class="badge ${bad?'bad':''}">${esc(v)}</span>`;}
function table(cols,rows){return `<div class="table-wrap"><table><thead><tr>${cols.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${cols.length}"><div class="empty">Нет записей</div></td></tr>`}</tbody></table></div>`;}
function pager(){return data?.total!==undefined?`<div class="pager">${btn('← Назад','prev','','',false)}<span class="muted">Страница ${page} · Всего ${esc(data.total)}</span>${btn('Далее →','next')}</div>`:'';}
function shell(){app.innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><span class="logo">В</span><div>Волна<div class="muted">Администратор</div></div></div><nav>${Object.entries(nav).map(([id,title])=>`<button data-action="nav" data-id="${id}" class="${view===id?'active':''}">${esc(title)}</button>`).join('')}</nav><div class="foot muted">${esc(session.phone)}<br>Версия ${esc(session.version)}<br>Сеанс до ${esc(date(session.expires))}</div></aside><main class="main"><header class="header"><div><h1>${esc(nav[view])}</h1><p class="muted">Управление мессенджером Волна</p></div><div class="actions">${btn('Обновить','refresh')}${btn('Выйти','logout')}</div></header><div id="content"><p class="loading">Загрузка…</p></div></main></div>`;}
function login(message=''){app.innerHTML=`<main class="login"><div class="logo">В</div><h1>Панель администратора</h1><p class="muted">Вход только по SMS на номер администратора. Код действует 5 минут.</p><form id="login-form"><label for="phone">Номер телефона</label><input id="phone" name="phone" type="tel" inputmode="tel" autocomplete="tel" placeholder="+7 968 141-12-41" required ${challenge?'readonly':''}>${challenge?'<label for="code">Код из SMS</label><input id="code" name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required>':''}<p class="error" id="login-error">${esc(message)}</p><button class="primary" ${!config.sms_enabled?'disabled':''}>${challenge?'Войти':'Получить SMS'}</button></form>${challenge?'<button data-action="resend">Запросить новый код</button>':''}<p class="muted">${config.sms_enabled?'Администратор: '+esc(config.phone_hint):'SMS не настроены. Проверьте NOTIFICORE_API_KEY и NOTIFICORE_ORIGINATOR на сервере.'}</p></main>`;const phone=document.querySelector('#phone');phone.value=login.phone||'';document.querySelector(challenge?'#code':'#phone')?.focus();}
async function load(){if(!session){config=await api('config');login();return;}const id=++loadId;shell();try{data=['announcement'].includes(view)?{}:await api(view+(view==='settings'||view==='stats'||view==='sms'||view==='backups'||view==='admin-sessions'?'':'?page='+page+'&q='+encodeURIComponent(query)+(view==='messages'&&chatFilter?'&chat='+chatFilter:'')));if(id!==loadId||!session)return;render();}catch(e){if(id===loadId&&session)document.querySelector('#content').innerHTML=`<div class="card error">${esc(e.message)}</div>`;}}
const search=()=>`<form id="search" class="toolbar"><input name="q" aria-label="Поиск" placeholder="Поиск по имени, тексту или ID" value="${esc(query)}"><button>Найти</button>${query?btn('Сбросить','clear'):''}</form>`;
function render(){let html='';
 if(view==='stats'){const c=data.counts;html=`<div class="metrics">${[['Пользователи',c.users],['Чаты',c.chats],['Сообщения',c.messages],['Файлы',c.files],['Хранилище',bytes(c.storage_bytes)],['Сеансы',c.active_sessions],['Заблокированы',c.blocked_users],['Звонки',data.active_calls.length]].map(([k,v])=>`<div class="metric"><span class="muted">${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}</div><div class="grid"><section class="card"><h2>Состояние сервера</h2><p>API и панель: ${badge('Работают')}</p><p>Распознавание: ${badge(data.whisper.available?(data.whisper.ready?'Готово':'Загружается'):'Недоступно',!data.whisper.available)}</p><p class="muted">${esc(data.whisper.state)} ${esc(data.whisper.model)}</p><p>Свободно: ${data.disk?bytes(data.disk.free_bytes):'Нет данных'}</p><p>Время работы: ${Math.floor(data.uptime_seconds/60)} мин.</p><p>Регистрация: ${data.settings.registration_enabled?'Открыта':'Закрыта'}</p><p>Обслуживание: ${data.settings.maintenance?'Включено':'Выключено'}</p></section><section class="card"><h2>Сообщения за последние дни</h2><div class="bars">${data.activity.slice().reverse().map(r=>`<div title="${esc(r.day)}: ${r.messages}" data-height="${Math.round(r.messages/Math.max(1,...data.activity.map(d=>d.messages))*100)}"></div>`).join('')}</div><p class="muted">Наведите на столбец, чтобы увидеть дату и количество.</p></section></div>`;}
 if(view==='users')html=search()+table(['ID / Имя','Телефон / Username','Активность','Статус','Управление'],data.items.map(r=>[`${esc(r.id)}<br><strong>${esc(r.name)}</strong>`,`${esc(r.phone)}<br>@${esc(r.username)}`,`${r.chats} чатов · ${r.messages} сообщений`,badge(r.admin_blocked?'Заблокирован':'Активен',r.admin_blocked),`<div class="actions">${btn('Профиль','user',r.id)}${btn(r.admin_blocked?'Разблокировать':'Блокировать','user-block',r.id,`data-value="${r.admin_blocked?'0':'1'}"`,!r.admin_blocked)}${btn('Завершить сеансы','user-sessions',r.id)}${btn('Обезличить','user-anonymize',r.id,'',true)}</div>`]))+pager();
 if(view==='chats')html=search()+`<div class="toolbar">${btn('Создать группу или канал','chat-create')}</div>`+table(['ID / Название','Тип','Участники / Сообщения','Статус','Управление'],data.items.map(r=>[`${r.id}<br><strong>${esc(r.title||'Личный чат')}</strong>`,esc(r.parent_id?'Подтема':r.kind),`${r.member_count} / ${r.message_count}`,badge(r.admin_deleted?'Удалён':r.admin_locked?'Заморожен':'Открыт',r.admin_deleted||r.admin_locked),`<div class="actions">${btn('Подробнее','chat',r.id)}${btn('Сообщения','chat-messages',r.id)}${btn(r.admin_locked?'Разморозить':'Заморозить','chat-lock',r.id,`data-value="${r.admin_locked?'0':'1'}"`)}${btn(r.admin_deleted?'Восстановить':'Удалить','chat-delete',r.id,`data-value="${r.admin_deleted?'restore':'delete'}"`,!r.admin_deleted)}</div>`]))+pager();
 if(view==='messages')html=search()+table(['ID / Чат','Автор','Текст / Вложение','Дата','Управление'],data.items.map(r=>[`${r.id}<br>Чат ${r.chat_id}`,esc(r.sender_name),`${r.deleted_at?badge('Удалено',true):esc(r.text)}<br><span class="muted">${esc(r.attachment_name)}</span>`,esc(date(r.created_at)),r.deleted_at?'—':`<div class="actions">${btn('Закрепить','message-pin',r.id,'data-value="1"')}${btn('Открепить','message-pin',r.id,'data-value="0"')}${btn('Удалить','message-delete',r.id,'',true)}</div>`]))+pager();
 if(view==='files')html=search()+`<p class="muted">Блокировка запрещает скачивание и повторную отправку. Используемые файлы сохраняются, чтобы не повредить базу.</p>`+table(['Файл','Владелец','Размер / Ссылки','Статус','Управление'],data.items.map(r=>[`${esc(r.name)}<br><span class="muted">${esc(r.mime)}</span>`,esc(r.owner_id),`${bytes(r.size)} / ${r.references_count}`,badge(r.admin_blocked?'Заблокирован':'Доступен',r.admin_blocked),`<div class="actions"><a href="/admin/api/files/${esc(r.id)}/download">Скачать</a>${btn(r.admin_blocked?'Разблокировать':'Блокировать','file-block',r.id,`data-value="${r.admin_blocked?'0':'1'}"`,!r.admin_blocked)}</div>`]))+pager()+`<div class="toolbar">${btn('Очистить неиспользуемые файлы','cleanup')}</div>`;
 if(view==='packs')html=search()+table(['Набор','Тип / Элементы','Автор','Статус','Управление'],data.items.map(r=>[esc(r.title),`${esc(r.kind)} / ${r.items}`,esc(r.owner_id),badge(r.status,r.status==='blocked'),btn(r.status==='blocked'?'Опубликовать':'Блокировать','pack',r.id,`data-value="${r.status==='blocked'?'published':'blocked'}"`,r.status!=='blocked')]))+pager();
 if(view==='sms')html=`<div class="card"><h2>Отправка SMS</h2><p>«Sent» означает принятие провайдером. Доставку проверяйте в кабинете Notificore.</p><p class="muted">Коды и ключ API в панели не показываются.</p>${btn('Сбросить лимит номера','sms-reset')}</div><h2>Вход в мессенджер</h2>`+table(['Reference','Номер','Статус','Попытки','Дата','Принято провайдером'],data.regular.map(r=>[esc(r.reference),esc(r.phone),badge(r.status,['failed','blocked'].includes(r.status)),r.attempts,esc(date(r.created)),r.provider_id?'Да':'Нет']))+`<h2 class="toolbar">Вход администратора</h2>`+table(['Reference','Статус','Попытки','Дата'],data.admin.map(r=>[esc(r.reference),esc(r.status),r.attempts,esc(date(r.created))]));
 if(view==='devices')html=table(['Пользователь','Платформа / Устройство','Последняя активность','Управление'],data.items.map(r=>[`${esc(r.name)}<br>${r.user_id}`,`${esc(r.platform)}<br><span class="muted">${esc(r.agent)}</span>`,esc(date(r.last_seen)),btn('Завершить сеанс','device',r.id,'',true)]))+pager();
 if(view==='calls')html=`<h2>Активные звонки</h2>`+table(['Чат','Участники','Статус','Управление'],data.active.map(r=>[r.chat_id,`${r.caller} → ${r.callee}`,esc(r.status),btn('Завершить','call',r.id,'',true)]))+`<h2 class="toolbar">История</h2>`+table(['Чат','Участники','Дата','Статус'],data.items.map(r=>[r.chat_id,`${r.caller} → ${r.callee}`,esc(date(r.created)),esc(r.status)]))+pager();
 if(view==='settings'){const labels={registration_enabled:'Разрешить регистрацию',maintenance:'Режим обслуживания',maintenance_message:'Сообщение об обслуживании',upload_max_mb:'Максимальный файл, МБ',user_storage_mb:'Квота пользователя, МБ',sms_phone_hour:'SMS на номер в час',sms_ip_hour:'SMS на IP в час',sms_day:'SMS на весь сервер в сутки'};html=`<form id="settings-form" class="card settings-form"><h2>Настройки сервера</h2>${Object.entries(data).map(([key,value])=>typeof value==='boolean'?`<label class="check"><input name="${key}" type="checkbox" ${value?'checked':''}>${esc(labels[key])}</label>`:`<label>${esc(labels[key])}</label><input name="${key}" type="${typeof value==='number'?'number':'text'}" value="${esc(value)}" required>`).join('')}<p class="muted">Обслуживание запрещает изменения в мессенджере. Панель остаётся доступна. Лимит SMS администратора: 5 в час.</p><button class="primary">Сохранить настройки</button></form>`;}
 if(view==='announcement')html=`<form id="announcement-form" class="card settings-form"><h2>Объявление всем пользователям</h2><p class="muted">Появится в канале «Новости Волны». Заблокированные аккаунты не включаются.</p><label>Текст</label><textarea name="text" maxlength="4000" required></textarea><button class="primary">Отправить объявление</button></form>`;
 if(view==='backups')html=`<div class="card"><h2>База и загруженные файлы</h2><p class="muted">Архив содержит снимок SQLite и папку uploads. Храните скачанную копию отдельно от сервера. Восстановление выполняется при остановленном сервере по инструкции ADMIN.md.</p>${btn(data.busy?'Копия создаётся…':'Создать резервную копию','backup')}</div>`+table(['Архив','Создан','Размер','Управление'],data.items.map(r=>[esc(r.filename),esc(date(r.created)),bytes(r.size),`<div class="actions"><a href="/admin/api/backups/${esc(r.id)}/download">Скачать</a>${btn('Удалить','backup-delete',r.id,'',true)}</div>`]));
 if(view==='audit')html=search()+table(['Дата / Администратор','Действие / Объект','Причина','Подробности'],data.items.map(r=>[`${esc(date(r.created))}<br>${esc(r.actor)}`,`${esc(r.action)}<br>${esc(r.target)}`,esc(r.reason),`<pre>${esc(r.details)}</pre>`]))+pager();
 if(view==='admin-sessions')html=table(['Устройство','IP','Последняя активность','Управление'],data.items.map(r=>[`${esc(r.agent)}${r.id===data.current_id?'<br>'+badge('Текущий'):''}`,esc(r.ip),esc(date(r.last_seen)),btn('Завершить','admin-session',r.id,'',true)]));
 document.querySelector('#content').innerHTML=html;document.querySelectorAll('[data-height]').forEach(e=>{e.style.height=e.dataset.height+'%';});
}
function dialog(title,content,onSubmit,{label='Подтвердить',danger=false}={}){modal.innerHTML=`<form id="dialog-form"><div class="modal-head"><h2>${esc(title)}</h2><button type="button" data-action="modal-close" aria-label="Закрыть">×</button></div>${content}<p class="error" id="modal-error"></p><div class="modal-actions"><button type="button" data-action="modal-close">Отмена</button><button class="${danger?'danger':'primary'}">${esc(label)}</button></div></form>`;modal.showModal();document.querySelector('#dialog-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await onSubmit(new FormData(e.target));modal.close();toast('Действие выполнено');await load();}catch(error){document.querySelector('#modal-error').textContent=error.message;}finally{b.disabled=false;}};}
const reasonField='<label>Причина действия</label><textarea name="reason" maxlength="500" required placeholder="Будет сохранена в журнале администратора"></textarea>';
function actionDialog(title,path,payload={},warning=''){dialog(title,`<p>${esc(warning||'Подтвердите действие. Изменение вступит в силу сразу.')}</p>${reasonField}`,f=>api(path,{...payload,reason:f.get('reason')}),{danger:true});}
async function userDialog(id){const r=await api('users/'+id);dialog('Профиль пользователя',`<dl class="detail"><dt>ID</dt><dd>${r.id}</dd><dt>Телефон</dt><dd>${esc(r.phone)}</dd><dt>Чатов</dt><dd>${r.chats.length}</dd><dt>Сеансов</dt><dd>${r.sessions.length}</dd></dl><label>Имя</label><input name="name" value="${esc(r.name)}" maxlength="64" required><label>Username</label><input name="username" value="${esc(r.username)}" required><label>Описание</label><textarea name="bio" maxlength="280">${esc(r.bio)}</textarea><label><input name="avatar_hidden" type="checkbox" ${r.avatar_hidden?'checked':''}>Скрыть аватар</label>${reasonField}`,f=>api('users/'+id,{name:f.get('name'),username:f.get('username'),bio:f.get('bio'),avatar_hidden:f.has('avatar_hidden'),reason:f.get('reason')}),{label:'Сохранить'});}
async function chatDialog(id){const r=await api('chats/'+id);const community=['group','channel'].includes(r.kind);const members=table(['Участник','Роль','Действия'],r.members.map(m=>[`${esc(m.name)}<br>${m.id}`,esc(m.role),community&&!r.parent_id?`<div class="actions">${btn('Роль','member-role',m.id,`data-chat="${id}"`)}${btn('Удалить','member-remove',m.id,`data-chat="${id}"`,true)}</div>`:'—']));dialog('Чат '+id,`<dl class="detail"><dt>Тип</dt><dd>${esc(r.kind)}</dd><dt>Состояние</dt><dd>${r.admin_deleted?'Удалён':r.admin_locked?'Заморожен':'Открыт'}</dd><dt>Ссылка</dt><dd>${r.invite?'Использований: '+r.invite.uses:'Нет приглашения'}</dd></dl>${community?`<label>Название</label><input name="title" value="${esc(r.title)}" maxlength="120" required><label>Описание</label><textarea name="description" maxlength="1000">${esc(r.description)}</textarea><label>Кто может писать</label><select name="posting_policy"><option value="all" ${r.posting_policy==='all'?'selected':''}>Все</option><option value="admins" ${r.posting_policy==='admins'?'selected':''}>Администраторы</option></select><label><input name="topic_closed" type="checkbox" ${r.topic_closed?'checked':''}>Подтема закрыта</label>${reasonField}`:''}<h2 class="toolbar">Участники</h2>${members}${community&&!r.parent_id?`<div class="toolbar">${btn('Добавить участника','member-add',id)}${btn('Отозвать приглашение','chat-invites',id)}</div>`:''}`,async f=>{if(community)await api('chats/'+id,{title:f.get('title'),description:f.get('description'),posting_policy:f.get('posting_policy'),topic_closed:f.has('topic_closed'),reason:f.get('reason')});},{label:community?'Сохранить':'Закрыть'});}
async function dispatch(b){const id=b.dataset.id,value=b.dataset.value;switch(b.dataset.action){
 case 'nav':view=id;page=1;query='';chatFilter='';await load();break;case 'refresh':await load();break;case 'prev':if(page>1){page--;await load();}break;case 'next':if(page*30<data.total){page++;await load();}break;case 'clear':query='';page=1;await load();break;
 case 'logout':await api('logout',{});session=null;challenge=null;login();break;case 'resend':challenge=null;login();break;case 'modal-close':modal.close();break;
 case 'user':await userDialog(id);break;case 'user-block':actionDialog(value==='1'?'Заблокировать аккаунт':'Разблокировать аккаунт','users/'+id+'/block',{blocked:value==='1'},value==='1'?'Все устройства пользователя будут отключены.':'Пользователь снова сможет войти по SMS.');break;
 case 'user-sessions':actionDialog('Завершить все сеансы','users/'+id+'/sessions',{confirm:id});break;case 'user-anonymize':actionDialog('Обезличить пользователя','users/'+id+'/anonymize',{confirm:id},'Телефон, имя, username и аватар будут заменены. Сообщения сохранятся. Действие необратимо.');break;
 case 'chat-create':dialog('Создать сообщество','<label>Название</label><input name="title" maxlength="80" required><label>Тип</label><select name="kind"><option value="group">Группа</option><option value="channel">Канал</option></select><label>ID владельца</label><input name="owner_id" type="number" min="1" required><p class="muted">ID зарегистрированного пользователя доступен в разделе «Пользователи».</p>'+reasonField,f=>api('chats',{title:f.get('title'),kind:f.get('kind'),owner_id:Number(f.get('owner_id')),reason:f.get('reason')}));break;
 case 'chat':await chatDialog(id);break;case 'chat-messages':view='messages';page=1;query='';chatFilter=id;await load();break;
 case 'chat-lock':actionDialog(value==='1'?'Заморозить чат':'Разморозить чат','chats/'+id+'/lock',{locked:value==='1'});break;case 'chat-delete':actionDialog(value==='delete'?'Удалить чат':'Восстановить чат','chats/'+id+'/'+value,{confirm:id},'Действие затронет чат и его подтемы. Удаление отзовёт приглашения и завершит звонки.');break;
 case 'chat-invites':modal.close();actionDialog('Отозвать приглашение','chats/'+id+'/invites');break;
 case 'member-add':case 'member-role':{const add=b.dataset.action==='member-add',chat=add?id:b.dataset.chat;modal.close();dialog(add?'Добавить участника':'Изменить роль',`${add?'<label>ID пользователя</label><input name="user_id" type="number" min="1" required>':'<p>ID: '+esc(id)+'</p>'}<label>Роль</label><select name="role"><option value="member">Участник</option><option value="admin">Администратор</option><option value="owner">Владелец</option></select><p class="muted">При назначении владельца прежний владелец станет администратором.</p>${reasonField}`,f=>api('chats/'+chat+'/members',{user_id:add?Number(f.get('user_id')):Number(id),operation:add?'add':'role',role:f.get('role'),reason:f.get('reason')}));break;}
 case 'member-remove':modal.close();actionDialog('Удалить участника','chats/'+b.dataset.chat+'/members',{user_id:Number(id),operation:'remove'});break;
 case 'message-delete':actionDialog('Удалить сообщение','messages/'+id+'/delete',{confirm:id},'Текст сообщения будет удалён для всех. Восстановить его из панели нельзя.');break;case 'message-pin':actionDialog(value==='1'?'Закрепить сообщение':'Открепить сообщение','messages/'+id+'/pin',{pinned:value==='1'});break;
 case 'file-block':actionDialog(value==='1'?'Заблокировать файл':'Разблокировать файл','files/'+id+'/block',{blocked:value==='1'});break;case 'cleanup':actionDialog('Очистить хранилище','maintenance/cleanup',{},'Удаляются только старые файлы, которые нигде не используются, и истёкшие задания уведомлений.');break;
 case 'pack':actionDialog(value==='blocked'?'Заблокировать набор':'Опубликовать набор','packs/'+id,{status:value});break;
 case 'device':actionDialog('Отключить устройство','devices/'+id+'/revoke');break;case 'call':actionDialog('Завершить звонок','calls/'+id+'/end');break;
 case 'sms-reset':dialog('Сбросить лимит SMS','<label>Номер в международном формате</label><input name="phone" type="tel" placeholder="+79001234567" required><p class="muted">Старые коды номера станут недействительны. Новый код пользователь запросит сам.</p>'+reasonField,f=>api('sms/reset',{phone:f.get('phone'),confirm:'RESET',reason:f.get('reason')}));break;
 case 'backup':actionDialog('Создать резервную копию','backups',{},'Архивация может занять несколько минут. Не закрывайте это окно до завершения.');break;case 'backup-delete':actionDialog('Удалить резервную копию','backups/'+id+'/delete',{confirm:id});break;case 'admin-session':actionDialog('Завершить сеанс администратора','admin-sessions/revoke',{id},'Для повторного входа потребуется новый SMS-код.');break;
 }}
app.addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(b)dispatch(b).catch(e=>toast(e.message));});modal.addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(b)dispatch(b).catch(e=>toast(e.message));});
app.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{
 if(e.target.id==='login-form'){const b=e.submitter;b.disabled=true;try{login.phone=f.get('phone');if(!challenge){challenge=await api('auth/request',{phone:login.phone});login();toast('SMS принято провайдером. Введите полученный код.');}else{await api('auth/verify',{sms_session_id:challenge.sms_session_id,code:f.get('code')});session=await api('session');challenge=null;await load();}}finally{b.disabled=false;}}
 if(e.target.id==='search'){query=f.get('q');page=1;await load();}
 if(e.target.id==='settings-form'){const settings={};for(const [key,v] of Object.entries(data))settings[key]=typeof v==='boolean'?f.has(key):typeof v==='number'?Number(f.get(key)):f.get(key);dialog('Сохранить настройки',reasonField,r=>api('settings',{settings,reason:r.get('reason')}));}
 if(e.target.id==='announcement-form')actionDialog('Отправить всем пользователям','announcement',{text:f.get('text'),confirm:'SEND'},'Объявление будет опубликовано в канале «Новости Волны» для всех активных пользователей.');
 }catch(error){const node=document.querySelector('#login-error');if(node)node.textContent=error.message;else toast(error.message);}});
try{config=await api('config');try{session=await api('session');await load();}catch{login();}}catch(e){app.innerHTML=`<main class="login"><h1>Панель недоступна</h1><p class="error">${esc(e.message)}</p><button data-action="refresh">Повторить</button></main>`;}
